### ISSUE TITLE
Demonstrate Dart calling into a .NET component via a CCW

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#112]
[Good suggestion](https://twitter.com/ThomasBurkhartB/status/1308475166805102592) from @escamoteur. 

Requires:

 - Add support for remaining COM Callable Wrapper interfaces (https://docs.microsoft.com/en-us/dotnet/standard/native-interop/com-callable-wrapper)
 - Create a trivial component in C# or similar, and create a tlb for it
 - Create a demo app that calls the C# component from Dart
 - Test, document and publish

**Comment by timsneath** [comment]
#111 takes care of the first one of these. Now to try it out.

**Comment by RustamG** [comment]
Hey @timsneath!

Any ETA on the remaining steps?

Thanks.

**Comment by timsneath** [comment]
Afraid not. I put this down to work on some other cool Win32 package-related things, and I haven't had a chance to pick it up again. I've marked it as 'help wanted' in case there are others who have the time to look at this specifically.
