### ISSUE TITLE
Simple input dialog

### ISSUE THREAD

**Issue by Merrit** [halildurmus/win32#119]
I've searched around, tried some of the examples. Very cool stuff!

Is there a way to show a simple input dialog? I am looking for a small window that a user can type into and return the value for use. Something like:

`int timerDuration = getInput();`

and the user could type 5 so a 5 minute timer could be set.

**Comment by timsneath** [comment]
From what kind of project? A Dart command line app? A traditional Win32 app like the DartNote example? A Flutter app?

There's no single Win32 API that is an input-style equivalent of `MessageBox`, as far as I know.

**Comment by Merrit** [comment]
Yeah, been researching more into win32 and it seems the answer is "it doesn't exist, make it yourself."

I was thinking it would be useful as something like a replacement for Zenity on Windows.

For example I have a bash script that runs this: `inputTime=$(zenity --entry --title "Set Timer" --text "Enter a new timer in minutes")`

Which is super fast and easy, [simple input box ](https://wiki.cdot.senecacollege.ca/w/imgs/thumb/Zenity_entry.png/200px-Zenity_entry.png) with no wait. Since I am not a fan of PowerShell I was hoping I could use a dart command line app as a replacement for this bash script on Windows - the popup input dialog being the easy / friendly way to give a quick input.

I threw together a barebones version with Flutter for the popup:

![image](https://user-images.githubusercontent.com/9575627/98543181-1174bc80-2260-11eb-92df-8410f865f424.png)

It works fine, and is suprisingly much faster than I expected - but still has a hickup for a second to load that I was hoping to have been ~instant.


I've spent the past few days tooling around with the win32 api for various things, but keep getting hung up on weirdness like it wanting a `hIcon`, and trying to figure out what data type that actually is and how to actually pass it from dart.. bit harder than I expected.

**Comment by timsneath** [comment]
Yeah, this makes it easy to call Win32 APIs from Dart, but doesn't make Win32 programming easy :) 

That said, it would be possible to translate something like this to Dart:
https://docs.microsoft.com/en-us/windows/win32/dlgbox/using-dialog-boxes

This uses the [CreateDialogIndirectParam](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdialogindirectparamw) function to display a classic Win32 dialog.

**Comment by Merrit** [comment]
> but doesn't make Win32 programming easy :)

Absolutely, I am really impressed with how much of the win32 api you have managed to wrangle! It's actually really interesting.

The biggest headache seems to be translating Microsoft's special variable names into an actual data type. Things like translating "DWORD" -> Uint32, HICON -> ???

I've actually just found [this dictionary](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types) that lists all the Windows data types, so that should help a lot.

I will give this another try. 😃

**Comment by timsneath** [comment]
Don't hesitate to shout out if you need other APIs wrapped that aren't wrapped today. I've got it down to a fine art :) 

`HICON` maps to an `IntPtr`, as with all other handles. On 64-bit systems, it's 8 bytes; on 32-bit systems, it's 4 bytes. Dart automatically translates `IntPtr` as appropriate.

**Comment by Merrit** [comment]
I tried setting this up, not quite there. Not sure what might be wrong at this point.

<details>
<summary>Details</summary>

```Dart
import 'dart:ffi';
import 'package:ffi/ffi.dart';

import 'package:win32/win32.dart';

void main() {

  final hInstance = GetModuleHandle(nullptr);

  var itemTemplate1 = DLGITEMTEMPLATE.allocate();
  var WS_EX_NOPARENTNOTIFY = 0x00000004;
  itemTemplate1.style = WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_GROUP;
  itemTemplate1.dwExtendedStyle = WS_EX_NOPARENTNOTIFY;
  itemTemplate1.x = 190;
  itemTemplate1.y = 160;
  itemTemplate1.cx = 50;
  itemTemplate1.cy = 14;
  itemTemplate1.id = 0;

  final lpTemplate = DLGTEMPLATE.allocate();
  lpTemplate.style = WS_POPUP | WS_VISIBLE;
  lpTemplate.dwExtendedStyle = WS_EX_TOPMOST;
  lpTemplate.cdit = 1; // Number of child elements, let's start with 1.
  lpTemplate.x = 0;
  lpTemplate.y = 0;
  lpTemplate.cx = 300;
  lpTemplate.cy = 200;
  lpTemplate.itemTemplate1 = itemTemplate1.addressOf;

  var lpDialogFunc = Pointer.fromFunction<DLGPROC>(dialogReturnProc, 0);

  var dwInitParam = WM_INITDIALOG;

  var hwnd = CreateDialogIndirectParamW(
    hInstance,
    lpTemplate.addressOf,
    NULL,
    lpDialogFunc,
    dwInitParam,
  );
}

int dialogReturnProc(int arg1, int arg2, int arg3, int arg4) {
  // This should have the return data from the dialog?
}


final _user32 = DynamicLibrary.open('user32.dll');

/// ```cpp
/// HWND CreateDialogIndirectParamW(
///   HINSTANCE       hInstance,
///   LPCDLGTEMPLATEW lpTemplate,
///   HWND            hWndParent,
///   DLGPROC         lpDialogFunc,
///   LPARAM          dwInitParam
/// );
/// ```
final CreateDialogIndirectParamW = _user32.lookupFunction<
    IntPtr Function(
        IntPtr hInstance,
        Pointer<DLGTEMPLATE> lpTemplate,
        IntPtr hWndParent,
        Pointer<NativeFunction> lpDialogFunc,
        IntPtr dwInitParam),
    int Function(
        int hInstance,
        Pointer<DLGTEMPLATE> lpTemplate,
        int hWndParent,
        Pointer<NativeFunction> lpDialogFunc,
        int dwInitParm)>('CreateDialogIndirectParamW');

/// ```cpp
/// DLGTEMPLATE structure (winuser.h)
///
/// Defines the dimensions and style of a dialog box. This structure,
/// always the first in a standard template for a dialog box, also specifies
/// the number of controls in the dialog box and therefore specifies the number
/// of subsequent DLGITEMTEMPLATE structures in the template.
///
/// typedef struct {
///   DWORD style;
///   DWORD dwExtendedStyle;
///   WORD  cdit;
///   short x;
///   short y;
///   short cx;
///   short cy;
/// } DLGTEMPLATE;
/// ```
class DLGTEMPLATE extends Struct {
  @Uint32()
  int style;

  @Uint32()
  int dwExtendedStyle;

  @Uint16()
  int cdit;

  @Int16()
  int x;

  @Int16()
  int y;

  @Int16()
  int cx;

  @Int16()
  int cy;

  Pointer<DLGITEMTEMPLATE> itemTemplate1;
  // Pointer<DLGITEMTEMPLATE> itemTemplate2;
  // Pointer<DLGITEMTEMPLATE> itemTemplate3;

  factory DLGTEMPLATE.allocate() => allocate<DLGTEMPLATE>().ref
    ..style = 0
    ..dwExtendedStyle = 0
    ..cdit = 0
    ..x = 0
    ..y = 0
    ..cx = 0
    ..cy = 0
    ..itemTemplate1 = nullptr;
  // ..itemTemplate2 = nullptr
  // ..itemTemplate3 = nullptr;
}

final WS_EX_TOPMOST = 0x00000008;

/// DLGITEMTEMPLATE structure (winuser.h)
///
/// Defines the dimensions and style of a control in a dialog box. One or more of
/// these structures are combined with a DLGTEMPLATE structure to form a standard
/// template for a dialog box.
///
/// ```cpp
/// typedef struct {
///   DWORD style;
///   DWORD dwExtendedStyle;
///   short x;
///   short y;
///   short cx;
///   short cy;
///   WORD  id;
/// } DLGITEMTEMPLATE;
/// ```
class DLGITEMTEMPLATE extends Struct {
  @Uint32()
  int style;

  @Uint32()
  int dwExtendedStyle;

  @Int16()
  int x;

  @Int16()
  int y;

  @Int16()
  int cx;

  @Int16()
  int cy;

  @Uint16()
  int id;

  factory DLGITEMTEMPLATE.allocate() => allocate<DLGITEMTEMPLATE>().ref
    ..style = 0
    ..dwExtendedStyle = 0
    ..x = 0
    ..y = 0
    ..cx = 0
    ..cy = 0
    ..id = 0;
}

/// DLGPROC callback function (winuser.h)
///
/// Application-defined callback function used with the CreateDialog and DialogBox
/// families of functions. It processes messages sent to a modal or modeless dialog
/// box. The DLGPROC type defines a pointer to this callback function. DialogProc
/// is a placeholder for the application-defined function name.
///
/// ```cpp
/// INT_PTR Dlgproc(
///   HWND Arg1,
///   UINT Arg2,
///   WPARAM Arg3,
///   LPARAM Arg4
/// )
/// ```
typedef DLGPROC = IntPtr Function(
    IntPtr Arg1, Uint32 Arg2, IntPtr Arg3, IntPtr Arg4);

```

</details>

My conclusion after dealing with the Windows API is that:
1. The Windows API is terrible. 😆 
2. You've done an amazing thing wrapping it into Dart!

I am not sure beating my head against this particular wall is worth it..
Perhaps I am just too new to programming, and I shouldn't be trying this after only a few months.

On the non-gui side of things, I did manage to create a working dart wrapper to suspend & resume processes that seems to work pretty well. Be happy to make a pull request if you would be interested in that sort of thing.

**Comment by timsneath** [comment]
I'll take a look over the weekend.  Looks like you have the basics right.

**Comment by timsneath** [comment]
Well, good golly, you certainly picked a nasty API surface! 

Most everything you did was perfect, but the struct here is barely a struct -- it's more a binary resource that is pseudo-represented by a struct, as this sample demonstrates:
https://docs.microsoft.com/en-us/windows/win32/dlgbox/using-dialog-boxes#creating-a-template-in-memory

That you got this far was impressive. I spent some time this morning making some further progress on your foundation. This displays a dialog with multiple child items:
https://github.com/timsneath/w32scratch/blob/main/bin/dialog.dart

It's not a million miles away from being useful, now the basics are in place. Feel free to clone and submit pull requests there.

**Comment by Merrit** [comment]
Yeah, that template was seriously challenging trying to understand. I am just getting to grips with what a 'struct' even is, and suddenly this thing is like structs within structs?

I am not even quite sure what you've done with it all to make it work, so I think I'll bow out of this one for now. You sure have a good handle on this API!

I will look into creating a pull request for an API feature I managed to get 100% working instead. 👍

**Comment by timsneath** [comment]
I've had fun playing with this, thank you for the suggestion. 

I've added this to the main repo as extension methods on `Pointer<DLGTEMPLATE>` and `Pointer<DLGITEMTEMPLATE>`, along with an example here: https://github.com/timsneath/win32/blob/master/example/dialogbox.dart
