### ISSUE TITLE
The function 'CreateCompatibleDC' isn't defined

### ISSUE THREAD

**Issue by Biacode** [halildurmus/win32#123]
Hi,
I am using the latest ^1.7.4 version of the library and the screenshot example has compile errors like
`The function 'CreateCompatibleDC' isn't defined.`
`The function 'SetStretchBltMode' isn't defined.`
`Undefined name 'BITMAP'.`
`The function 'StretchBlt' isn't defined.`
etc.

**Comment by Biacode** [comment]
I am able to find the functions in the project repository, but they don't exist in deployed lib `gdi32.dart`

**Comment by timsneath** [comment]
Yup -- they're part of the upcoming 2.0.0 release. If you have a null-safe version of Dart (e.g. Flutter `beta` channel), you can use the prerelease, here: https://pub.dev/packages/win32/versions/2.0.0-nullsafety.7
