### ISSUE TITLE
Add String setters to many structs

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#142]

**Comment by timsneath** [comment]
This will be much easier when we have fixed-sized arrays in FFI structs. I can add something by hand if it's needed, but when arrays land, I can replace many lines of boilerplate with something much cleaner here.

**Comment by timsneath** [comment]
Fixed in the latest Dart builds: https://github.com/dart-lang/sdk/issues/35763 

I can start working on this now in the partitioned dart2.13 branch: https://github.com/timsneath/win32/tree/dart2.13

**Comment by timsneath** [comment]
Fixed in https://github.com/timsneath/win32/commit/a1a1d4321c8730d92b00cc56e89a7b21f9e48a42

**Comment by Sunbreak** [comment]
How could we turn `Array<Int8>` into/from `String` efficently? Code below works but copied the internal data

https://github.com/woodemi/twaindsm.dart/blob/6caefd76590fa59938f9f60184bede5814d00ef6/lib/structs.dart#L273-L288

```dart
extension CharArray on Array<Int8> {
  String getDartString(int maxLength) {
    var list = <int>[];
    for (var i = 0; i < maxLength; i++) {
      if (this[i] != 0) list.add(this[i]);
    }
    return utf8.decode(list);
  }

  void setDartString(String s, int maxLength) {
    var list = utf8.encode(s);
    for (var i = 0; i < maxLength; i++) {
      this[i] = i < list.length ? list[i] : 0;
    }
  }
}
```

**Comment by timsneath** [comment]
My guess is that, while inefficient, the performance cost of the copy is tiny compared to the Win32 calls themselves. If it's only a few thousand instructions, it's probably not worth worrying about. But curious if you've measured this?

**Comment by Sunbreak** [comment]
Related: https://github.com/dart-lang/sdk/issues/45508
