### ISSUE TITLE
Breaking change in nullsafety.8

### ISSUE THREAD

**Issue by stuartmorgan-g** [halildurmus/win32#145]
I'm in the process of migrating path_provider_windows to null-safety, and between when I started the patch (where I set the version constraint to `^2.0.0-nullsafety.7`) and today, it broke:
```
../lib/src/path_provider_windows_real.dart(34,47): error GDAEE715C: The argument type 'Pointer<IntPtr>' can't be assigned to the parameter type 'Pointer<Pointer<NativeType>>'. [C:\b\s\w\ir\k\plugins\packages\path_provider\path_provider_windows\example\build\windows\flutter\flutter_assemble.vcxproj]
../lib/src/path_provider_windows_real.dart(123,33): error GB1B8BC88: Method not found: 'GUID.fromString'. [C:\b\s\w\ir\k\plugins\packages\path_provider\path_provider_windows\example\build\windows\flutter\flutter_assemble.vcxproj]
../lib/src/path_provider_windows_real.dart(129,9): error GDAEE715C: The argument type 'Pointer<IntPtr>' can't be assigned to the parameter type 'Pointer<Pointer<Utf16>>'. [C:\b\s\w\ir\k\plugins\packages\path_provider\path_provider_windows\example\build\windows\flutter\flutter_assemble.vcxproj]
```

Was breaking semver in the nullsafety releases intentional? It makes the migration trickier.

**Comment by timsneath** [comment]
Unfortunately FFI changed in a way that breaks me, so you can no longer add a factory constructor like `GUID.fromString()` to a `Struct`. And FFI itself hasn't reached a stable release.

(FWIW, as I understand it, semver doesn't guarantee stability between pre-release versions. https://semver.org/#spec-item-9.)

More generally, I'm allowing for some minor breaking changes now (as noted in the README) as I stabilize and publish my 2.0 release based on the FFI stable release. With the work I've put in over these pre-releases, I feel confident that this will be a stable API contract moving forward.
