### ISSUE TITLE
GetAsyncKeyState

### ISSUE THREAD

**Issue by GameMakerJake** [halildurmus/win32#149]
Any plans to support `GetAsyncKeyState`? I know the Win32 API pretty well and having looked through the codebase it seems like I may be able to contribute some time to this project. It's paramount this project (or another) supports various Win32 API calls.

Is there a roadmap, or any support channels that allow contributors to discuss?

Thank you :)

**Comment by timsneath** [comment]
A roadmap would be nice! This has primarily been me scratching my programming itch in little chunks of free time. But it would be good to build one out. Right now my focus is on stabilizing the 2.0 release. If you'd be interested in pitching in, the big need in the immediate weeks ahead is testing, more examples and polish. 

Feel free to add useful APIs (like `GetAsyncKeyState`) that you think I'm missing -- the CONTRIBUTING.md file describes how to add new metadata to the JSON file that is used to generate all the FFI code and tests. 

When 2.0 is out the door, I want to explore the new [Win32 metadata](https://blogs.windows.com/windowsdeveloper/2021/01/21/making-win32-apis-more-accessible-to-more-languages/) stuff from Microsoft. In particular, I want to improve COM and WinRT interop, within the limitations of the current Dart FFI implementation.

**Comment by timsneath** [comment]
I've added `GetAsyncKeyState` and most of the other APIs in https://docs.microsoft.com/en-us/windows/win32/api/_inputdev/. But your contributions remain appreciated!
