### ISSUE TITLE
GetKeyboardState does not change the result after the first read

### ISSUE THREAD

**Issue by PlugFox** [halildurmus/win32#153]
GetKeyboardState does not change the result after the first read

Example:
```dart
final lpKeyboardState = calloc.allocate<Uint8>(256);
final timer = Timer.periodic(const Duration(milliseconds: 250), (_) {
  GetKeyboardState(lpKeyboardState);
  print(' * Left Shift state: ${lpKeyboardState.elementAt(160).value}');
});
await Future.delayed(const Duration(seconds: 10)).whenComplete(() {
  timer.cancel();
  calloc.free(lpKeyboardState);
});
```

**Comment by timsneath** [comment]
I think this is unrelated to win32. A quick search on SO suggests that you have to pump the message loop in order to get a new status. https://stackoverflow.com/questions/37142779/getkeyboardstate-cant-detect-while-i-am-pressing-the-key
