### ISSUE TITLE
Lost response after changing window size.

### ISSUE THREAD

**Issue by tilongzs** [halildurmus/win32#157]
The 1.26.0-12.0.pre version of flutter does not have this problem.
After the flutter is updated to the latest version (DEV or 1.27.0-4.0pre), the program stops responding after modifying the window size through MoveWindow or SetWindowPos interface.

` if (_hwnd != 0) {
      MoveWindow(_hwnd, 100, 100, 600, 400, 1);
    }  else {
      print('_hwnd == 0');
    }`
![2021-02-19_165709](https://user-images.githubusercontent.com/18590422/108481763-892c9b80-72d3-11eb-8734-0a2a36700dd8.jpg)

**Comment by timsneath** [comment]
Hmm, that's strange. Are you able to provide a small repro that I can test? Which version of `win32` are you using?

**Comment by tilongzs** [comment]
> Hmm, that's strange. Are you able to provide a small repro that I can test? Which version of `win32` are you using?

https://github.com/tilongzs/win32_movewindow_test.git

Flutter: DEV
win32: ^1.7.4+1

**Comment by timsneath** [comment]
I took a look at your code and I don't think the problem is related to the `win32` package. 

The challenge is that your `MoveWindow` call clashes with the `WM_SIZE` event in `win32_window_cpp`:

```c
        case WM_SIZE:
        {
              RECT rect = GetClientArea();
              if (child_content_ != nullptr) {
                // Size and position the child window.
                MoveWindow(child_content_, rect.left, rect.top, rect.right - rect.left,
                           rect.bottom - rect.top, TRUE);
              }
            return 0;
        }
```

and I think the two get into a deadlock. 

For what it's worth, you should upgrade to win32 2.0.0 or greater if you're targeting Dart 2.12.0-259.9 or greater, since there are breaking changes in FFI in recent releases to the `dev` and `beta` channel.

**Comment by tilongzs** [comment]
> I took a look at your code and I don't think the problem is related to the `win32` package.
> 
> The challenge is that your `MoveWindow` call clashes with the `WM_SIZE` event in `win32_window_cpp`:
> 
> ```c
>         case WM_SIZE:
>         {
>               RECT rect = GetClientArea();
>               if (child_content_ != nullptr) {
>                 // Size and position the child window.
>                 MoveWindow(child_content_, rect.left, rect.top, rect.right - rect.left,
>                            rect.bottom - rect.top, TRUE);
>               }
>             return 0;
>         }
> ```
> 
> and I think the two get into a deadlock.
> 
> For what it's worth, you should upgrade to win32 2.0.0 or greater if you're targeting Dart 2.12.0-259.9 or greater, since there are breaking changes in FFI in recent releases to the `dev` and `beta` channel.

But even if I use Win32 2.0.0, this problem still exists. Is there no solution at the moment?

**Comment by timsneath** [comment]
I'm surprised this ever worked, unless the Flutter runner itself has changed. The WM_SIZE code above is in the Windows runner that is generated when you create `flutter create`. In any event, this isn't a bug in `win32`, I don't think. My code is successfully calling `MoveWindow`, as can be demonstrated by commenting out the WM_SIZE code above in your generated code (windows\runner\win32_window.cpp).

**Comment by tomaszpolanski** [comment]
I also can confirm that it stopped working for me as well.
The last working version of Flutter that I've tested was `1.25.0-8.2.pre` and now I am trying out `1.26.0-17.8.pre` and it's not working. Therefore it was introduced between `1.26.0-12.0.pre` and `1.26.0-17.8.pre`.
Definitely, this is an issue coming from Flutter and not this package

**Comment by tomaszpolanski** [comment]
@tilongzs Do you create your own window and then change the position OR do you look up an existing window and change it?
In Tim's example, he is creating his own window and in my code (also probably yours) we look up Flutter's windows - maybe that's the issue

**Comment by tilongzs** [comment]
@tomaszpolanski @timsneath 
I found a solution. By modifying the (windows\runner\win32_window.cpp) file, create a custom message that delays the code WM_SIZE the modified sub-window in "Windows".
Please refer to the modified records in https://github.com/tilongzs/win32_movewindow_test.git.
