### ISSUE TITLE
Empty structs are undefined behavior

### ISSUE THREAD

**Issue by jackselvam** [halildurmus/win32#158]
Flutter 1.27.0-5.0.pre.92 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2c5c509486 (19 hours ago) • 2021-02-20 15:11:04 -0500
Engine • revision b793775d2a
Tools • Dart 2.13.0 (build 2.13.0-52.0.dev)

Error:

/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(1111,7): error G09587AA0: Struct 'ENUMLOGFONTEX' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2835,7): error G09587AA0: Struct 'BLUETOOTH_PIN_INFO' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2960,7): error G09587AA0: Struct 'EXCEPINFO' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2966,7): error G09587AA0: Struct 'PROPERTYKEY' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2973,7): error G09587AA0: Struct 'PROPVARIANT' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2978,7): error G09587AA0: Struct 'SAFEARRAY' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2985,7): error G09587AA0: Struct 'CLSID' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2992,7): error G09587AA0: Struct 'STATSTG' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart(2999,7): error G09587AA0: Struct 'NLM_SIMULATED_PROFILE_INFO' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart(47,33): error G733AAF94: Expected type 'T' to be a valid 
and instantiated subtype of 'NativeType'. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom build for 'D:\Project\SKS_Software\skssoftware\build\windows\CMakeFiles\95511d9335ae4f8a8157b88f8092fde2\flutter_windows.dll.rule;D:\Project\SKS_Software\skssoftware\build\windows\CMakeFiles\8da1cc372f83ce643b7c8f38b68565c3\flutter_assemble.rule' exited with code 1. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by maxnemoy** [comment]
@jackselvam, Flutter master, has deprecated some dart:ffi features  (https://github.com/flutter/flutter/issues/76485), try https://pub.dev/packages/win32/versions/2.0.0
