### ISSUE TITLE
[Discussion] Should we free `TEXT`? 

### ISSUE THREAD

**Issue by Sunbreak** [halildurmus/win32#178]
https://github.com/timsneath/win32/blob/cc4870102e95b0c2cf0f4ca31e15baa1f783fe9e/lib/src/utils.dart#L22

`TEXT` uses `toNativeUtf16`, which uses `allocator`

https://github.com/dart-lang/ffi/blob/24eb0a066d3b32e54682a57e4780af4e2efbd2d3/lib/src/utf16.dart#L76-L83

```dart
  Pointer<Utf16> toNativeUtf16({Allocator allocator = malloc}) {
    final units = codeUnits;
    final Pointer<Uint16> result = allocator<Uint16>(units.length + 1);
    final Uint16List nativeString = result.asTypedList(units.length + 1);
    nativeString.setRange(0, units.length, units);
    nativeString[units.length] = 0;
    return result.cast();
  }
```

But code in samples doesn't take care of `free`

https://github.com/timsneath/win32/blob/cc4870102e95b0c2cf0f4ca31e15baa1f783fe9e/example/hello.dart#L41

Related: https://github.com/dart-lang/ffi/issues/86

**Comment by timsneath** [comment]
Yes, you absolutely should. Sorry -- some of my samples are very shoddy in this regard, since they're short lived and the process will free up the memory on exit. I've gradually moved some of them over to use a `try... finally` block, but I should fix up the rest.

**Comment by timsneath** [comment]
I've made a number of fixes to this in the short term. As you say, it's important to do this in production code, but it makes some of the samples rather painful to read because of all the allocation / deallocation. Ultimately I'd like to fix this by using the `Pool` feature so that these are automatically deallocated when they fall out of scope.

**Comment by Sunbreak** [comment]
BTW, should we free `Pointer<COMObject>` in object from `CoCreateInstance` ?

https://github.com/timsneath/win32/blob/a608e2e47c8c6f2cc94180b4de101592b308a54c/example/wmi.dart#L43-L57

```dart
if (FAILED(hr)) {
  // ...
  free(pLoc.ptr);
  CoUninitialize();
  throw exception; 
}
```

**Comment by timsneath** [comment]
I think I've fixed all instances of this; please reopen if you find any further leaks.
