### ISSUE TITLE
GetLastError() fails.

### ISSUE THREAD

**Issue by krjw-eyev** [halildurmus/win32#189]
In this simple example GetLastError() returns 0 although it should return 100. I might do something wrong here.

```
import 'dart:ffi';

final _kernel32 = DynamicLibrary.open('kernel32.dll');

int GetLastError() {
  final _GetLastError = _kernel32.lookupFunction<Uint32 Function(), int Function()>('GetLastError');
  return _GetLastError();
}

void SetLastError(int dwErrCode) {
  final _SetLastError = _kernel32.lookupFunction<Void Function(Uint32 dwErrCode), void Function(int dwErrCode)>('SetLastError');
  return _SetLastError(dwErrCode);
}

main(List<String> args) async {
  SetLastError(100);
  await Future.delayed(Duration(milliseconds: 200));
  final ret = GetLastError();
  print(ret);
}

```

This could be related to how ffi works in terms of calling native functions.

**Comment by timsneath** [comment]
I've noticed this too, although I wasn't smart enough to try setting an error to confirm this. @dcharkes this might potentially be an FFI issue if other calls overwrite the thread last error value? https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror

**Comment by krjw-eyev** [comment]
That was my initial thought too! node-ffi has the same problem too https://github.com/node-ffi/node-ffi/issues/261.
Unfortunately this has not been touched in nearly 4 years.

Do you think we should report this to the dart-lang team? I have tried to figure out where this might happen... 
https://github.com/dart-lang/sdk/blob/master/runtime/lib/ffi.cc

Here they call SetLastError
https://github.com/dart-lang/sdk/blob/master/runtime/lib/ffi_dynamic_library.cc

**Comment by dcharkes** [comment]
Hey! This is a known issue.

> this might potentially be an FFI issue if other calls overwrite the thread last error value

Yes it is. Any thread local storage can be clobbered by other calls happening in the mean time. (E.g. the VM might do a garbage collection or something else and call OS API's in the mean time.)

We're tracking this on https://github.com/dart-lang/sdk/issues/38832.

**Comment by krjw-eyev** [comment]
Should we close this issue then, since it has nothing to do with this lib? Maybe add something to README so people know about this?

**Comment by Sunbreak** [comment]
We'd better hide the `GetLastError` until it works: https://github.com/timsneath/win32/pull/382/files
