### ISSUE TITLE
SetParent

### ISSUE THREAD

**Issue by keinou** [halildurmus/win32#193]
Example for SetParent usage?

For example, run notepad and SetParent this inside a Container()

**Comment by timsneath** [comment]
Can you explain further? Are you asking about how to use the Win32 `SetParent` API in general? 

Or are you asking about hosting a window inside a Flutter desktop app?

**Comment by keinou** [comment]
In C# to put an external program inside a panel we use SetParent, what I need to do is the same thing, for example:

Run any program, like paint or notepad and after that take your window into my application, so that it is "docked", for example:

![image](https://user-images.githubusercontent.com/20158261/113032902-67d68f00-915e-11eb-95a0-1c9c366b788d.png)
