### ISSUE TITLE
Memory leak in interface getters

### ISSUE THREAD

**Issue by efreibe** [halildurmus/win32#198]
I've been looking at the code trying to implement some interfaces.

I've noted that at the end of getters there is a `free` statement to release memory allocated earlier, but if the native function does not succeed an exception is thrown and the memory is not freed. 

Let's take for example a code snipped taken from [IFileOpenPicker.dart](https://github.com/timsneath/win32/blob/2eaf004a1107d93e5039df8b491246363688a264/lib/src/com/IFileOpenPicker.dart), you'll see what I mean:

```dart
  int get FileTypeFilter {
    final retValuePtr = calloc<IntPtr>();

    final hr = Pointer<NativeFunction<_get_FileTypeFilter_Native>>.fromAddress(
            ptr.ref.vtable.elementAt(14).value)
        .asFunction<_get_FileTypeFilter_Dart>()(ptr.ref.lpVtbl, retValuePtr);
    if (FAILED(hr)) throw WindowsException(hr);

    final retValue = retValuePtr.value;
    free(retValuePtr);
    return retValue;
  }
```

Because the pointer is generated inside the function it must be freed even if another type of exception is thrown (ie, calling `.fromAddress`, `.asFunction`, etc.)

**Comment by timsneath** [comment]
Yeah, that totally needs fixing. Thanks for the heads-up.

**Comment by efreibe** [comment]
I think that ffi needs to have any type of smart pointer because it's a nightmare to have to deal with freeing them at this point. Something realated to finalizers maybe?

I don't know if you have any solution for this or any workaround to avoid memory leaks before posting the issue in dart ffi.

Another issue that maybe could need to be addressed here is auto releasing interfaces (implemented in IUnknown) before garbage collection, maybe using finalizers too. I've tried to understand how they works but cannot find any working example.

**Comment by timsneath** [comment]
We do have some samples of resource management here: 
https://github.com/dart-lang/sdk/tree/master/samples/ffi/resource_management

This introduces the concept of a `Pool`, which can take care of releasing resources automatically when they fall out of scope. I haven't yet looked at implementing this at the library level.
