### ISSUE TITLE
Windows Serial#

### ISSUE THREAD

**Issue by natgross** [halildurmus/win32#200]
Can I get the Windows 10 serial number with this pkg?

**Comment by timsneath** [comment]
I don't know. It depends on what you mean by 'serial number' (do you mean 'product key'? or 'computer serial number'? or 'Windows 10 version'?)

In general, it's helpful if you tell me the Win32 API you're trying to access, and I can always add it if it's missing.

**Comment by natgross** [comment]
Either a hardware serial# (didn't know I can get that in windows) or the product key. I need to uniquely id every device on the network. In Android there are several pkg's on pub.dev that give me the Android ID, which is guaranteed (by Google) to be unique across all Android devices. So, any hacker-proof way of getting a unique # on windows 10, is fine by me.
I have been holding off migrating my android-flutter app to the desktop, for this one reason. Hence my question.
