### ISSUE TITLE
WinRT `bool`s don't project correctly

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#225]
For example, `GetNationalDirectDialingPrefixForRegion` takes a bool for `stripNonDigit`. This should be represented as:

```dart
typedef _GetNationalDirectDialingPrefixForRegion_Native = Int32 Function(
    Pointer obj,
    IntPtr regionCode,
    /* Boolean */ Uint8 stripNonDigit,
    Pointer<IntPtr> result);
typedef _GetNationalDirectDialingPrefixForRegion_Dart = int Function(
    Pointer obj, int regionCode, int stripNonDigit, Pointer<IntPtr> result);

  int GetNationalDirectDialingPrefixForRegion(
          int regionCode, bool stripNonDigit, Pointer<IntPtr> result) =>
      Pointer<
                  NativeFunction<
                      _GetNationalDirectDialingPrefixForRegion_Native>>.fromAddress(ptr
                  .ref.vtable
                  .elementAt(8)
                  .value)
              .asFunction<_GetNationalDirectDialingPrefixForRegion_Dart>()(
          ptr.ref.lpVtbl, regionCode, stripNonDigit ? 1 : 0, result);
```

Note the Dart `typedef` takes an `int` and the function wrapper should convert.

**Comment by Sunbreak** [comment]
https://github.com/dart-lang/sdk/issues/36855 seems resolved

**Comment by timsneath** [comment]
Thanks. I've fixed this in the `namespace` branch, but there's still quite a lot of work to do before I can merge this in.

**Comment by timsneath** [comment]
Fixed in b2d8831756abe439a2ce8b8e51ef0943921500f4

**Comment by Sunbreak** [comment]
A little curious. Is https://github.com/timsneath/win32/commit/b2d8831756abe439a2ce8b8e51ef0943921500f4 related to `bool` projection?

**Comment by timsneath** [comment]
Sorry, I can understand the confusion! 

That commit itself isn't the fix: that came when the overall projection library was overhauled, along with the work in dart:ffi to support the `Bool` ABI type. But this should now work -- the commit b2d8831 contains a working test (to my best understanding) that uses the `Bool` type.

Let me know if you're expecting to see something different, @Sunbreak!
