### ISSUE TITLE
Add support for ApplicationData.LocalSettings API's

### ISSUE THREAD

**Issue by clarkezone** [halildurmus/win32#228]
Required by uwp version of the `path_provider` plugin: https://github.com/flutter/flutter/issues/70206

https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localsettings?view=winrt-19041

**Comment by timsneath** [comment]
Currently blocked on https://github.com/dart-lang/sdk/issues/46004

**Comment by timsneath** [comment]
These APIs are only available to UWP apps or apps with an established package identify, and since we're not supporting UWP from Flutter any more, I'm closing this for now. There are viable ways to achieve this in Win32 already for non-UWP apps.

**Comment by clarkezone** [comment]
I thought packageidentity was available to win32 apps

**Comment by timsneath** [comment]
Technically, yes, but it requires a whole bunch of crazy sparse packaging registration stuff to be done: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps

I don't understand why anyone would go through this pain, particularly when similar COM APIs are available without all this ceremony. Maybe there's some reason to add all this overhead to a Windows developer, but I'm a bit lost as to what it could be.
