### ISSUE TITLE
shobjidl_core.h

### ISSUE THREAD

**Issue by youk** [halildurmus/win32#231]
Hello there,

Would it be possible to provide wrappers to interfaces from [shobjidl_core.h](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/)? I am particularly interested in [IShellLinkA](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ishelllinka)/[IShellLinkW](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ishelllinkw).

Thanks.

**Comment by timsneath** [comment]
Of course! I've added `IShellLink` and a few related ones to the main branch. At the moment, I'm still adding these interfaces manually as I improve and verify the generation code, so please let me know if you need other ones and I'll add them as quickly as I can.

**Comment by timsneath** [comment]
v2.1.2 is published, including these changes: https://pub.dev/packages/win32

**Comment by youk** [comment]
Thanks!

Can we also have factory method just as in https://github.com/timsneath/win32/blob/main/lib/src/com/IShellItem.dart#L92?

**Comment by timsneath** [comment]
Oh -- good catch. The Unicode name (`IShellLinkW`) messed up my code generator. I've fixed this in b91ad90, but I'd like to write a small test to make sure that this works correctly. I'll do that and then publish.

**Comment by timsneath** [comment]
v2.1.3 includes a working version. 

I've created a small example of its use: https://github.com/timsneath/win32/blob/d8f04121d5ed5c42b9e4c89098adf626f471b267/example/shortcut.dart

**Comment by youk** [comment]
Thanks for quick response. I was able to create and persist a link.

BTW, https://github.com/timsneath/win32/blob/d8f04121d5ed5c42b9e4c89098adf626f471b267/example/shortcut.dart#L35 gives me STATUS_HEAP_CORRUPTION. I didn't look much into it – is the memory already freed at that point?

**Comment by timsneath** [comment]
Yeah, I think you may be right. Looks like there's a double free bug there.
I'll take a proper look this evening.

**Comment by timsneath** [comment]
I think I've caught it -- can you try again?

**Comment by youk** [comment]
It's ok now.
