### ISSUE TITLE
win32 DCB structure feature

### ISSUE THREAD

**Issue by FengChendian** [halildurmus/win32#233]
Hello,
I can't find  [DCB](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-dcb) struct in this package. Would it be possible to provide wrappers to DCB interfaces in winbase.h? It's important to implement serial port communication.
Thanks.

**Comment by timsneath** [comment]
Of course! I've updated the main branch with this and added a number of relevant Win32 APIs. 

Please let me know if you need anything else.

**Comment by timsneath** [comment]
v2.1.2 is published, including these changes: https://pub.dev/packages/win32

**Comment by FengChendian** [comment]
Thanks for quick updates! Now I can find DCB struct.

But I have a little problem about setting DCB parameters.
In C++, I can
```c++
DCB dcbSerialParameters = {0};
if (!GetCommState(this->handler, &dcbSerialParameters))
{
    std::cerr << "Failed to get current serial parameters\n";
} else
{
    dcbSerialParameters.BaudRate = CBR_115200;
}
```
How can I set dcbSerialParameters in dart? I try
```dart
final dcb = DCB();
dcb.BaudRate = 115200;
```
But I met "Exited (3221225477)"

**Comment by timsneath** [comment]
You need to do something like:

```dart
final dcb = calloc<DCB>();
dcb.ref.BaudRate = 115200;
```

`DCB` has to be natively allocated (hence the `calloc`). The first line returns a `Pointer<DCB>`, and then you can access the underlying members using the `.ref` property.

**Comment by FengChendian** [comment]
Thanks! Now I know how to use native Struct.

BTW, I found when I open "COM5" using dart, the handle always euqal -1. But I can open this port sucessfully with similar C++ code.
Because of GetLastError() #189 problem, I don't know if this is my code bug or package bug. When https://github.com/dart-lang/sdk/issues/38832 fixed, I will track this. Here is my dart code:
```dart
final portName = TEXT("COM5");

final handler = CreateFile(portName, GENERIC_ALL, 0, nullptr, OPEN_EXISTING,
    FILE_ATTRIBUTE_NORMAL, NULL);

if (handler == INVALID_HANDLE_VALUE) {
  final lastError = GetLastError();
  if (lastError == ERROR_FILE_NOT_FOUND) {
    print(portName.toDartString() + "is not available");
  } else {
    print('get ${lastError}');
  }
  print("handler error");
  return;
}
```

**Comment by timsneath** [comment]
I added an example here:
https://github.com/timsneath/win32/blob/ac9a8bc7febc11f04e57da105b122c3941b23b0c/example/serial.dart

This seems to work successfully on my machine at least:
```
[C:\src\win32] dart example\serial.dart
BaudRate = 1200, ByteSize = 7, Parity = 2, StopBits = 0
BaudRate = 57600, ByteSize = 8, Parity = 0, StopBits = 0
```

**Comment by FengChendian** [comment]
LOL... After compare with the example, I found my code bug. I use `GENERIC_ALL` instead of`GENERIC_READ | GENERIC_WRITE` in dart. 
Now it worked! Thank you very much!
