### ISSUE TITLE
winscard

### ISSUE THREAD

**Issue by generikvault** [halildurmus/win32#237]
Hello there,

can you add support for winscard?

https://docs.microsoft.com/de-de/windows/win32/api/winscard/

thanks

**Comment by timsneath** [comment]
Yeah, that's quite a lot of APIs to wrap. Can you tell me more about how you plan to use these APIs? Do you need all of them?

Also, feel free to submit a PR for this work -- that might be the best way to get this done...

**Comment by generikvault** [comment]
Yes, that's a lot.
We have a java health care application that we wanna port to flutter. The german health care card is a smart card.  One must have feature of the app is reading the patient's meta data from this card.
So my plan is to write a dart smart card package using [pcsclite](https://pcsclite.apdu.fr/) for mac/linux and winscard for windows. Highlevel functionality would be list readers, register a listener and receive card data via this listener. 

So thats basicly all I have for know.

**Comment by timsneath** [comment]
Ok I've added these APIs. Hope this is useful; please let me know if you find something missing!

**Comment by generikvault** [comment]
Thank you. I didn't made much progress yet. I'll get in touch as soon as I produced something thats actually runs.
