### ISSUE TITLE
How to add win32 constants

### ISSUE THREAD

**Issue by generikvault** [halildurmus/win32#269]
Hi,  I tried to add some winscard functions to this package.

I've found `win32api.json` and `win32struct.json` for generating classes and structs.

Do you have already a concept for constants or should I better manage them in my own package for now?

**Comment by timsneath** [comment]
Hi there!

You can add them directly to this file: https://github.com/timsneath/win32/blob/main/lib/src/constants.dart 

Constants aren't autogenerated at present.

**Comment by generikvault** [comment]
That will do the job. Thank you.
