### ISSUE TITLE
Use `Builder` for code generation

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#275]
Switch from the manual code generation step to using Builder. An example for this scenario (thanks @kevmoo) can be found here:
https://github.com/dart-lang/build/blob/master/example/lib/example.dart#L11-L30

A few notes for myself:

- Input will be a file (`tool/win32api.json` or similar)
- Output will be `*.g.dart` or similar
- Need to keep the `buildExtensions` and `build.yaml` entries consistent
- Can write multiple output files from one input file in the `build()` method 

Jake is the right go-to person.

**Comment by timsneath** [comment]
From https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md: 
> A Builder must have outputs that are known statically based on input paths and file extensions. For example an input named foo.dart always results in an output named foo.something.dart. Builders are not allowed to read the input in order to determine outputs. The only outputs that can be produced are those which share a file base name with an input.

https://github.com/dart-lang/build/blame/master/docs/writing_an_aggregate_builder.md suggests that a builder can take multiple inputs, but still only one output. This may invalidate `build` as a useful way for us to create our projection, since we don't really want to either a) create a separate input file for every output file, or b) create a single output file for all inputs.

**Comment by halildurmus** [comment]
Yes, I noticed that too, and was about to tell you about it.
