### ISSUE TITLE
Support Notifications?

### ISSUE THREAD

**Issue by UNIcodeX** [halildurmus/win32#279]
Would it be possible to add support for the windows notification area? If that functionality already exists, then please excuse my request, as I did not see an example dart file for it.

https://docs.microsoft.com/en-us/windows/win32/shell/notification-area

**Comment by ilopX** [comment]
https://github.com/timsneath/win32/tree/main/example/shell_notify_icon

**Comment by timsneath** [comment]
Thanks, @ilopX (both for the original sample and answering the question!)

@UNIcodeX, I'm going to close this for now; let me know if you see something missing that you need after inspecting this example.

**Comment by UNIcodeX** [comment]
This is just for an icon in the tray, right? I'm looking for pop up notification boxes with text in them.

**Comment by ilopX** [comment]
> This is just for an icon in the tray, right? I'm looking for pop up notification boxes with text in them.

https://github.com/alexmercerind/desktoasts
