### ISSUE TITLE
Adding Win32 functions?

### ISSUE THREAD

**Issue by bezubaba** [halildurmus/win32#290]
Inside Kernel32.dart it says
// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

How am I suppose to add additional function?
For example there is no CreateFileMappingA defined inside the kernel32.dart.

**Comment by ilopX** [comment]
> When wrapping a Win32 API, use the Unicode ('W') wide variants of these APIs, rather than the ANSI ('A') variants. For example: CredWriteW, rather than CredWriteA.
> 
> To create a new API, don't edit the main library files themselves; these get overwritten. Instead, edit tool\manual_gen\win32api.json and run tool\generate.cmd to update the library files. This might seem a pain, but it gives protection against any changes to dart:ffi, since the typedef syntax can be easily recreated as necessary.

https://github.com/timsneath/win32/blob/main/CONTRIBUTING.md
