### ISSUE TITLE
I can't get the UID because it returns a different value each time.

### ISSUE THREAD

**Issue by Mevius21** [halildurmus/win32#309]
The pbSendBuffer in the SCardTransmit part of winscard is supposed to return a pointer, but the value is overwritten each time and a different value is returned, so I can't get the UID.
Is there another way to get the uid?

**Comment by Mevius21** [comment]
It also appears that the [0xff, 0xca, 0x00, 0x00, 0x00] data in pbSendBuffer is ignored.

**Comment by timsneath** [comment]
I'm sorry -- I don't have a smart card attached to my Windows machine, so I can't test this. 

I'd assume that your code doesn't match the equivalent C++ Win32 code, since Dart just passes through to the underlying Win32 API.

**Comment by Mevius21** [comment]
I see.
Thank you.
