### ISSUE TITLE
cant hide cursor

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [halildurmus/win32#313]
setting `SetCursor(0)` or `ShowCursor(0)` does not hide the cursor

**Comment by timsneath** [comment]
In what context? In a Flutter app?

**Comment by abdelaziz-mahdy** [comment]
Yes on Flutter desktop app(windows) when I called those functions and trying different parameters nothing happened 
But showcursor returns the count right it's just the cursor doesn't get hidden

**Comment by abdelaziz-mahdy** [comment]
any updates?

**Comment by timsneath** [comment]
Oh, yeah, Flutter doesn't use the Win32 API to paint the cursor. This won't do anything in that context. 

You probably want something like this code (untested by me, just a hit for 'hide cursor flutter'):
https://stackoverflow.com/questions/59620886/hide-the-texfield-cursor-in-flutter

**Comment by user1121114685** [comment]
`import 'dart:async';
import 'package:flutter/material.dart';
import 'package:win32/win32.dart';
import 'dart:ffi';
import 'package:ffi/ffi.dart';

class MouseDetectionWidget extends StatefulWidget {
  @override
  _MouseDetectionWidgetState createState() => _MouseDetectionWidgetState();
}

class _MouseDetectionWidgetState extends State<MouseDetectionWidget> {
  Timer? _detectionTimer;
  Timer? _hideCursorTimer;
  Offset? _lastMousePosition;
  bool _cursorVisible = true;

  void _updateCursorVisibility() {
    if (_cursorVisible) {
      // 如果光标当前是可见的，隐藏它
      SetCursor(NULL);
    } else {
      // 如果光标当前是隐藏的，显示它
      SetSystemCursor(CopyIcon(LoadCursor(NULL, IDC_ARROW)), OCR_NORMAL);
    }
  }

  @override
  void initState() {
    super.initState();
    _detectionTimer = Timer.periodic(const Duration(milliseconds: 200), (timer) {
      if (_hideCursorTimer == null || !_hideCursorTimer!.isActive) {
        // 如果隐藏光标的计时器还没有启动或者已经停止
        _hideCursorTimer = Timer(const Duration(seconds: 5), () {
          setState(() {
            _cursorVisible = false; // 隐藏光标
            _updateCursorVisibility(); // 更新光标的可见性
          });
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onHover: (PointerHoverEvent event) {
        if (_lastMousePosition != event.position) {
          _lastMousePosition = event.position; // 更新鼠标位置
          _cursorVisible = true; // 显示光标
          _updateCursorVisibility(); // 更新光标的可见性
          _hideCursorTimer?.cancel(); // 重置隐藏光标的计时器
          _hideCursorTimer = Timer(const Duration(seconds: 5), () {
            setState(() {
              _cursorVisible = false; // 5秒后隐藏光标
              _updateCursorVisibility(); // 更新光标的可见性
            });
          });
        }
      },
      cursor: _cursorVisible ? SystemMouseCursors.basic : SystemMouseCursors.none,
      child: Container(
        // 这里是您的子部件
      ),
    );
  }

  @override
  void dispose() {
    _detectionTimer?.cancel(); // 确保检测鼠标位置的计时器被取消
    _hideCursorTimer?.cancel(); // 确保隐藏光标的计时器被取消
    super.dispose();
  }
}
`
I'm doing the same thing, I want to hide the mouse pointer instead of the cursor pointer on a flutter windows program, but that didn't work.

**Comment by abdelaziz-mahdy** [comment]
> `import 'dart:async';
> import 'package:flutter/material.dart';
> import 'package:win32/win32.dart';
> import 'dart:ffi';
> import 'package:ffi/ffi.dart';
> 
> class MouseDetectionWidget extends StatefulWidget {
>   @override
>   _MouseDetectionWidgetState createState() => _MouseDetectionWidgetState();
> }
> 
> class _MouseDetectionWidgetState extends State<MouseDetectionWidget> {
>   Timer? _detectionTimer;
>   Timer? _hideCursorTimer;
>   Offset? _lastMousePosition;
>   bool _cursorVisible = true;
> 
>   void _updateCursorVisibility() {
>     if (_cursorVisible) {
>       // 如果光标当前是可见的，隐藏它
>       SetCursor(NULL);
>     } else {
>       // 如果光标当前是隐藏的，显示它
>       SetSystemCursor(CopyIcon(LoadCursor(NULL, IDC_ARROW)), OCR_NORMAL);
>     }
>   }
> 
>   @override
>   void initState() {
>     super.initState();
>     _detectionTimer = Timer.periodic(const Duration(milliseconds: 200), (timer) {
>       if (_hideCursorTimer == null || !_hideCursorTimer!.isActive) {
>         // 如果隐藏光标的计时器还没有启动或者已经停止
>         _hideCursorTimer = Timer(const Duration(seconds: 5), () {
>           setState(() {
>             _cursorVisible = false; // 隐藏光标
>             _updateCursorVisibility(); // 更新光标的可见性
>           });
>         });
>       }
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MouseRegion(
>       onHover: (PointerHoverEvent event) {
>         if (_lastMousePosition != event.position) {
>           _lastMousePosition = event.position; // 更新鼠标位置
>           _cursorVisible = true; // 显示光标
>           _updateCursorVisibility(); // 更新光标的可见性
>           _hideCursorTimer?.cancel(); // 重置隐藏光标的计时器
>           _hideCursorTimer = Timer(const Duration(seconds: 5), () {
>             setState(() {
>               _cursorVisible = false; // 5秒后隐藏光标
>               _updateCursorVisibility(); // 更新光标的可见性
>             });
>           });
>         }
>       },
>       cursor: _cursorVisible ? SystemMouseCursors.basic : SystemMouseCursors.none,
>       child: Container(
>         // 这里是您的子部件
>       ),
>     );
>   }
> 
>   @override
>   void dispose() {
>     _detectionTimer?.cancel(); // 确保检测鼠标位置的计时器被取消
>     _hideCursorTimer?.cancel(); // 确保隐藏光标的计时器被取消
>     super.dispose();
>   }
> }
> `
> I'm doing the same thing, I want to hide the mouse pointer instead of the cursor pointer on a flutter windows program, but that didn't work.
> 

Windows cursor can be hidden using flutter widget that defines the cursor look I don't remember the name now

**Comment by user1121114685** [comment]
int ShowCursor(int bShow) => _ShowCursor(bShow);

final _ShowCursor = _user32.lookupFunction<Int32 Function(Int32 bShow),
    int Function(int bShow)>('ShowCursor');`

---
This method of hiding the mouse also does not work. It may be because this parameter is wrong. You should use BOOL bShow and pass it in as a parameter.
---
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\WinUser.h
---


int
WINAPI
ShowCursor(
    _In_ BOOL bShow);

**Comment by user1121114685** [comment]
> Windows cursor can be hidden using flutter widget that defines the cursor look I don't remember the name now

```
// 鼠标检查间隔，越小检查频率越高越浪费
constexpr int MOUSE_IDLE_TIME = 500;

// 鼠标是否隐藏
bool is_mouse_hidden = false;

// 上次鼠标位置
POINT last_cursor_pos = { 0, 0 };

// 定时器ID
UINT_PTR timer_id = 0;

int cursor_index = 0;

// 定时器回调函数
VOID CALLBACK TimerProc(HWND hwnd, UINT message, UINT_PTR id, DWORD time) {
    POINT cursor_pos;
    GetCursorPos(&cursor_pos);

    if (cursor_pos.x == last_cursor_pos.x && cursor_pos.y == last_cursor_pos.y) {
        // 鼠标未移动，隐藏鼠标
        if (!is_mouse_hidden) {
            cursor_index++;
            // 如果大于10次就是5秒就隐藏鼠标
            if (cursor_index > 9) {
                ShowCursor(FALSE);
                is_mouse_hidden = true;
            }
        }
    }
    else {
        // 鼠标移动，显示鼠标
        if (is_mouse_hidden) {
            ShowCursor(TRUE);
            is_mouse_hidden = false;
            cursor_index = 0;
        }

        // 更新鼠标位置
        last_cursor_pos = cursor_pos;
    }
}
```
```
  // 创建定时器
  timer_id = SetTimer(NULL, 0, MOUSE_IDLE_TIME, TimerProc);
    // 销毁定时器
  KillTimer(NULL, timer_id);
```

I have actually implemented it in c++, but it is not perfect. I only want to enable it when the player is playing, not all the time. If it can work on dart, it will be perfect!

**Comment by abdelaziz-mahdy** [comment]
Nice find, I was stuck with that problem without knowing the cause, and then used the flutter widget to hide it , 

So thank you for sharing the fix
