### ISSUE TITLE
Raw input

### ISSUE THREAD

**Issue by Zekfad** [halildurmus/win32#323]
Hi, is it possible to add projections for raw input APIs?
Here is [MS Docs](https://docs.microsoft.com/en-us/windows/win32/inputdev/using-raw-input)
Some key APIs are:
- [RegisterRawInputDevices](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerrawinputdevices)
- [GetRawInputData](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdata)
- [RAWINPUTDEVICE](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinputdevice) struct
- [RAWINPUT](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinput) struct

**Comment by timsneath** [comment]
Totally. Give me 24 hours, and I should be able to make that happen...

**Comment by Zekfad** [comment]
Thanks for your attention and quickness!
