### ISSUE TITLE
Raw input related constants

### ISSUE THREAD

**Issue by Zekfad** [halildurmus/win32#326]
Hi! Recently you've closed #323 and that's very cool, but there are some helpful constants missing:
- [HID usages](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/hid-usages) (e.g. `HID_USAGE_GENERIC_MOUSE`)
- [Raw Input Device constants](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinputdevice) (such as `RIDEV_NOLEGACY`, `RIDEV_INPUTSINK` etc.)

Could you add them, please?

**Comment by timsneath** [comment]
Aaargh! I thought I'd caught all of them. 

Yeah, I can add them. In the meantime, they're just const values, so obviously you're welcome to just declare them yourself in your code as you need them. For example:

```dart
const HID_USAGE_GENERIC_MOUSE = 0x02;
```

**Comment by timsneath** [comment]
(Oh, and also feel free to submit a PR to this file https://github.com/timsneath/win32/blob/main/lib/src/constants.dart, if you want this sooner!)

**Comment by Zekfad** [comment]
Yeah, I've done it that like that while I was playing around with it.
Just found it helpful for anyone who will ever use raw input with win32 dart.
