### ISSUE TITLE
CreateDIBSection missing

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [halildurmus/win32#333]
Hi,

For a new project I need `CreateDIBSection`, but it isn't available yet in this library.
I got it working by looking at the other win32 calls. Would you like a PR for the code?

**Comment by h3x4d3c1m4l** [comment]
I see this effort already progressing very nicely which would probably solve this issue...

https://github.com/timsneath/win32/pull/319

**Comment by timsneath** [comment]
Yeah, that's easy to add. Any others that you might need while I'm updating?

**Comment by h3x4d3c1m4l** [comment]
Nope, it was just this one! Needed it to be able to grab the RAW image very fast en easy from memory after doing BitBlt from memory to the bitmap created by CreateDIBSection.

Thanks!

**Comment by timsneath** [comment]
Of course! Fixed in https://github.com/timsneath/win32/commit/f581cb52b7a48c71e87dbaedc40ae6390fcd8a2c, which will be momentarily published as v2.3.2. Thanks for using win32!
