### ISSUE TITLE
GetActiveWindow() does not work as expected

### ISSUE THREAD

**Issue by damywise** [halildurmus/win32#336]
I expect it to return the window's handle, but it returns 0 instead.
I think I need the handle from GetActiveWindow() to be able to use PostMessage().
For example:
I want to minimize the window using `PostMessage(hWnd, WM_SYSCOMMAND, SC_MINIMIZE, 0);` but it won't work whatever I do.
It DOES work for other windows when I tried using WM_BROADCAST.

**Comment by krll-kov** [comment]
> k I need the handle from GetActiveWindow() to be able to use PostMes

That's probably a handle issue, try retrieving handle by flutter's app class name(FLUTTER_RUNNER_WIN32_WINDOW) with FindWindowEx function.

One more way to retrieve handle is EnumWindows. You can call GetWindowThreadProcessId for each window and compare it with GetCurrentProcessId()
