### ISSUE TITLE
any possible way to implement camera?

### ISSUE THREAD

**Issue by kechankrisna** [halildurmus/win32#340]
Is that possible to take picker from windows(built in camera or external camera)? That would be so helpful to for flutter on windows. Thank you

**Comment by timsneath** [comment]
Yeah, it's totally possible. We wouldn't build this directly into the win32 package, rather it would make sense to be part of the broader camera package, whether it used the Dart Win32 bindings or called into them via C++. We're planning something along those lines "soon"... stay tuned.
