### ISSUE TITLE
Remove conflict with `Char` in `dart:ffi`

### ISSUE THREAD

**Issue by dcharkes** [halildurmus/win32#349]
https://dart-review.googlesource.com/c/sdk/+/228541 added a `Char` type to `dart:ffi`.

Unfortunately that breaks `package:win32` and in turn the Flutter build: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8824468064587445729/+/u/Android_Views_Integration_Tests/stdout

The easiest fix would be to just `import 'dart:ffi' hide Char;` in https://github.com/timsneath/win32/blob/main/lib/src/structs.g.dart.

(And then release a new version, and roll that into Flutter, and any packages that are used in Flutter and roll those into Flutter.)

**Comment by timsneath** [comment]
@dcharkes This is fixed in win32 v2.3.8.

**Comment by a-siva** [comment]
Can we close this issue ?

**Comment by timsneath** [comment]
It's closed, no?
