### ISSUE TITLE
flutter build web error

### ISSUE THREAD

**Issue by sleepreading** [halildurmus/win32#352]
import but not used(check platform type, skip if web).

```
Error: Only JS interop members may be 'external'.
  external int wBitsPerSample;
....
....
/D:/tmp/.pub/cache/hosted/pub.flutter-io.cn/win32-2.3.1/lib/src/combase.dart:24:37:
Error: Only JS interop members may be 'external'.
  external Pointer<Pointer<IntPtr>> lpVtbl;
                                    ^
Error: Compilation failed.
```

**Comment by sleepreading** [comment]
Turn's out, It's another plugin problem, not this one.

**Comment by varunbhalerao56** [comment]
@sleepreading how did you find out which plugin? I have quite a lot of dependencies, tried removing which I thought were the issue but no luck

**Comment by sleepreading** [comment]
@varunbhalerao56  I use this plugin https://github.com/leanflutter/launch_at_startup/issues/2#event-5946585105.
As the author said he has fixed this issue.
