### ISSUE TITLE
add support for mapi32.dll

### ISSUE THREAD

**Issue by ekuleshov** [halildurmus/win32#353]
Please add support of APIs from mapi32.dll, e.g. `SendMail`

**Comment by timsneath** [comment]
As I understand it, `SendMail` isn't a Windows API, it's part of Outlook. https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/mapi-programming-overview

It looks like earlier versions of Windows included a stub library, but even that's now gone: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/windowsmapi/mapi32-stub-library

**Comment by ekuleshov-idexx** [comment]
Maybe you right, though that is the api being referred to for creating new emails and not only with Outlook. Eg. see this reference article https://docs.microsoft.com/en-us/previous-versions/windows/desktop/windowsmapi/mapi32-stub-library
