### ISSUE TITLE
Is there a way to react on WM_KILLFOCUS in flutter app

### ISSUE THREAD

**Issue by sturkopf123** [halildurmus/win32#355]
In more detail, is it possible to react in flutter on "WM_KLIIFOCUS" such that for example the user of the app could get locked out again in order to prevent security issues.

**Comment by domesticmouse** [comment]
@sturkopf123 I suspect this issue has been posted in the wrong issue tracker. If you are asking questions about the Flutter Win32 embedder, the correct issue tracker to ask questions on is https://github.com/flutter/flutter/issues.

Alternatively, if you are asking about @timsneath's [`win32_runner`](https://github.com/timsneath/win32_runner), then the correct issue tracker is https://github.com/timsneath/win32_runner/issues.
