### ISSUE TITLE
Error when get packages in pubspec.yaml

### ISSUE THREAD

**Issue by shinxxxxwon** [halildurmus/win32#361]
After adding the latest version of `win32: ^2.3.11` to the pubspec.yaml file as a dependency, an error occurs when pub get is performed. The error message is:
```
The current Dart SDK version is 2.15.0-116.0.dev.

Because stack_over depends on win32 >=2.3.7 which requires SDK version >=2.15.0 <3.0.0, version solving failed.
pub get failed (1; Because stack_over depends on win32 >=2.3.7 which requires SDK version >=2.15.0 <3.0.0, version solving failed.)
```

**Comment by timsneath** [comment]
Looks like you need a later version of Dart.

Flutter 2.10 includes Dart 2.16.0, which satisfies your requirements.
