### ISSUE TITLE
Memory manipulation API in Dart

### ISSUE THREAD

**Issue by Hexer10** [halildurmus/win32#37]
Hi,
I was wondering if the aim of this library was to provide ffi only for ui api or also low end memory manipulation functions such as `ReadProcessMemory`, `WriteProcessMemory`, `EnumProcesses`, `EnumProcessModules`, ...
If so could they be implemented anytime in the future, for some I could also make a PR, but I couldn't find anyway to port `EnumProcessModules` , since it requires an array as parameter and I couldn't find any documentation about that.

**Comment by timsneath** [comment]
Hi there, let me take a look at these: I'm keen to add APIs based on user needs. Would love to hear more about your use case, if you're willing to share!

**Comment by Hexer10** [comment]
So first of all I've updated the issue with the right functions which were [ReadProcessMemory](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-readprocessmemory) and [WriteProcessMemory](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-writeprocessmemory)).
I'd like to use them just to manipulate other processes memory (`OpenProcess` should be implemented to use those functions as well as  `CloseHandle` to cleanupthe code after), and for the `EnumProcess*` I'd use them like here: [EnumProcesses](https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-modules-for-a-process) and [EnumProcessModules](https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-processes).
(The additional api included in those example include: [GetModuleFileNameEx ](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulefilenameexw) and [GetModuleBaseName](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulebasenamew))

**Comment by timsneath** [comment]
APIs added in v1.6.0, along with an example that demonstrates their use:
https://github.com/timsneath/win32/blob/master/example/modules.dart

Hopefully this does what you need!
