### ISSUE TITLE
bluetooth low energy support

### ISSUE THREAD

**Issue by rohitsangwan01** [halildurmus/win32#370]
hey , great package and i know this package already support bluetooth apis , but can we please have a bluetooth low energy support for connection/disconnection ,   read/write and subscription to characteristics data

**Comment by rohitsangwan01** [comment]
@timsneath for refrence , there is a package quick_blue , which already supports ble for windows  https://github.com/woodemi/quick_blue/tree/master/quick_blue_windows/windows

**Comment by insertjokehere** [comment]
Hi @timsneath - we are also interested in being able to access the BLE libraries using this library rather than having to build our own C++ bindings. Did you have a rough idea of how you would tackle this? I'm keen to give it a shot, but don't have a good idea where to start.

**Comment by timsneath** [comment]
I'm blocked by https://github.com/microsoft/win32metadata/issues/843, unfortunately. Hopefully that will be addressed, and then I can complete support for this.

**Comment by timsneath** [comment]
Fixed in #380 now that Microsoft have addressed the issue above.

**Comment by rohitsangwan01** [comment]
Great , Thank you so much

**Comment by insertjokehere** [comment]
Thank you!
