### ISSUE TITLE
How to send keyboard events to a specified window？

### ISSUE THREAD

**Issue by chomoe327** [halildurmus/win32#371]
This is a great project, I really like it, but I have some questions while using it .
I studied ```sendInput.dart``` but didn't find the parameter to set the window handle.
I got the window handle using the ```FindWindowEx``` function, but I don't know how to use it.
Any suggestion?

**Comment by ilopX** [comment]
SendInput only works on the active window.

```dart
  final hwnd = FindWindow(TEXT('notepad'), nullptr);

  if (hwnd == 0) {
    throw 'Window not found';
  }

  ShowWindowAsync(hwnd, SW_RESTORE);
  SetForegroundWindow(hwnd);

  final kbd = calloc<INPUT>();
  kbd.ref.type = INPUT_KEYBOARD;
  kbd.ref.ki.wVk = VK_A;
  vSendInput(1, kbd, sizeOf<INPUT>());
  ....

```

**Comment by ilopX** [comment]
You can also use the SendMessage command. But then you need to know the exact descriptor.

```dart
  final hwnd = FindWindow(TEXT('notepad'), nullptr);
  final editor = FindWindowEx(hwnd, 0, TEXT('Edit'), nullptr);

  if (hwnd == 0) {
    throw 'Editor not found';
  }

  final ilopX = [0x49, 0x4C, 0x4F, 0x50, 0x58];

  for (final virtualKey in ilopX) {
    SendMessage(editor, WM_CHAR, virtualKey, 0); 
    Sleep(500);
  }
```

**Comment by chomoe327** [comment]
> SendInput only works on the active window.
> 
> ```dart
>   final hwnd = FindWindow(TEXT('notepad'), nullptr);
> 
>   if (hwnd == 0) {
>     throw 'Window not found';
>   }
> 
>   ShowWindowAsync(hwnd, SW_RESTORE);
>   SetForegroundWindow(hwnd);
> 
>   final kbd = calloc<INPUT>();
>   kbd.ref.type = INPUT_KEYBOARD;
>   kbd.ref.ki.wVk = VK_A;
>   vSendInput(1, kbd, sizeOf<INPUT>());
>   ....
> ```

Thanks for the answer, it really helped me！
