### ISSUE TITLE
running app on win7 is not support?

### ISSUE THREAD

**Issue by baneyue** [halildurmus/win32#374]
how can i do ?

![156954092-76356956-17a2-4551-85c7-d727b4a67e2f](https://user-images.githubusercontent.com/1902581/156976384-f4026811-2308-49bc-8be2-112bfa56a81f.png)
![156954137-27b0e344-f27c-41d2-85c4-318aa5a64964](https://user-images.githubusercontent.com/1902581/156976398-ccd8479f-abf4-4543-b465-d0b026a17e7f.png)
![156954370-7c68e33b-93c5-482e-97ba-8084e70f140f](https://user-images.githubusercontent.com/1902581/156976407-d3415c1e-38ca-4b65-9de6-726a516da5bd.jpg)
![156975972-b5144d27-4907-4041-ab68-33865b4de0d7](https://user-images.githubusercontent.com/1902581/156976418-6a7ef207-dc29-405b-bb84-e13136f1aae4.png)

**Comment by timsneath** [comment]
Correct, `GetDpiForWindow` isn't supported on Windows 7. 

But an app that imports win32 should work on Windows 7 **unless** it calls an unsupported method. Does your code call this function?

**Comment by baneyue** [comment]
bitsdojo_window has use this api

![image](https://user-images.githubusercontent.com/1902581/157146571-38f955de-5ebb-4256-a8e3-d26e98e4f317.png)

**Comment by timsneath** [comment]
Ok, then that's a bug in bitsdojo. They could check version before calling this function, or declare support only for Windows 10.

**Comment by AllanChen** [comment]
Acturelly, It had already fixed. 
Solution 1:
https://github.com/bitsdojo/bitsdojo_window/issues/53
Solution 2:
https://github.com/bitsdojo/bitsdojo_window/pull/100

I recommend Solution 2. (朋友，第二个会靠谱点)

**Comment by timsneath** [comment]
Thanks! Then, I'm going to close this issue because I don't think it's a bug in this package. Hopefully that's OK!
