### ISSUE TITLE
Bluetooth serial

### ISSUE THREAD

**Issue by nico3587** [halildurmus/win32#400]
Hello,

I tried to use the example for bluetooth, but I always have "Bluetooth radio is not discoverable" message and "no devices found". Is there somethings to do to have discoverable enable ?
The main goal of this is to have serial communication over Bluetooth with a device. I have succeed on Android with package "flutter_bluetooth_serial" and I have to do the same on windows.
I don't no if I can do this with the "win32" package, but any help or advise would be very welcomed.

kind regards,

Nicolas Hallynck

**Comment by timsneath** [comment]
Hi there! Thanks for the report. On investigating, I found a bug in the Bluetooth example where it wasn't setting the size of the struct correctly. I've updated it (https://github.com/timsneath/win32/commit/9d7b6346bd076a1c5ab3d2ea8479360096eb8b30), and now it seems to be working for me:

https://github.com/timsneath/win32/blob/9d7b6346bd076a1c5ab3d2ea8479360096eb8b30/example/bluetooth.dart

```
[C:\src\win32] dart example\bluetooth.dart
Found a radio with handle: 0x00000250
Radio name: TIM-SURFACE
Radio address: 03:55:55:8E:34:C8
Bluetooth radio is discoverable.
Device address: 52:D6:90:6B:88:70
  Name: GID6B
  Authenticated: True
  Connected: True
  Remembered: True
Device address: CC:66:75:CD:69:C8
  Name:
  Authenticated: False
  Connected: False
  Remembered: False
```

Give the updated version a try and see if it works for you?

**Comment by nico3587** [comment]
Hi,

Thanks for the update. I've tested it and it 's working now for me also.

**Comment by timsneath** [comment]
Great! Thanks again for spotting this!

**Comment by tegarnugroho** [comment]
Hi @timsneath , is it possible to search for a Bluetooth device that is not yet connected to a Windows device? because currently when I try to run the example at https://github.com/dart-windows/win32/blob/main/example/bluetooth.dart it only shows connected bluetooth devices.
