### ISSUE TITLE
[Feature request] Add Inapp-purchase api

### ISSUE THREAD

**Issue by tbm98** [halildurmus/win32#401]
Currently, I see [inapp_purchase](https://pub.dev/packages/in_app_purchase) doesn't support Windows yet. And I research and found this sample implement iap for Windows by cpp. [sample](https://github.com/Microsoft/Windows-universal-samples/blob/main/Samples/Store/cpp). 
But I don't know how to use it in Flutter project, Can you support this api in Win32 package or give me some suggestions to do it ?

**Comment by timsneath** [comment]
This would be best implemented by inapp_purchase. 

This is what's called a federated plugin, meaning that a motivated Windows developer could build a Windows-only implementation in C++ that matches the common API, just as the StoreKit version does for Apple: https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase_storekit

If you have C++ skills, I'd encourage you to work on a PR there. The WinRT API here doesn't lend itself well to invocation from Dart (today, at least).
