### ISSUE TITLE
How to access WbemRefresher?

### ISSUE THREAD

**Issue by kolyneh** [halildurmus/win32#408]
I want to access performance data as documented here: 
[https://docs.microsoft.com/en-us/windows/win32/wmisdk/accessing-performance-data-in-c--](url)
But I can't find the `WbemRefresher` class.

**Comment by kolyneh** [comment]
@timsneath 
Hi Tim:

I'm not working on Windows, but with your project I think it'll easy for me to make a  flutter app works with Windows features.
I had make my `WbemRefresher` implementation , and I code a test demo following this doc:
 [https://docs.microsoft.com/en-us/windows/win32/wmisdk/accessing-wmi-preinstalled-performance-classes](https://docs.microsoft.com/en-us/windows/win32/wmisdk/accessing-wmi-preinstalled-performance-classes).
But with no luck I failed. 

The demo is here: [my_flutter_win32_example](https://github.com/kolyneh/my_flutter_win32_example)
App crash without logs at this line [test_win32.dart line 212](https://github.com/kolyneh/my_flutter_win32_example/blob/6b5d5cc9052b56d458fa9f622ae5cebca5935251/lib/test_win32.dart#L212)

Could you please help me to figure out what's wrong there?
Thanks!

**Comment by timsneath** [comment]
Thanks - this is helpful. Forgive me, though -- it might be a day or two before I can take a look: this is a side-project, not my day job...

**Comment by timsneath** [comment]
I think you were very close, just that you needed a `.cast()` instead of a `.value` for one of the retrieved COM objects.

I've updated the project with a new example that ports the Microsoft sample code you were drafting off, here:
https://github.com/timsneath/win32/blob/main/example/wmi_perf.dart

**Comment by kolyneh** [comment]
Sorry for my poor perception of COM, but thank you!
I'll check it later.

**Comment by kolyneh** [comment]
It works very well! Now I can easily get the data of `Win32_PerfFormattedData`.
Thanks Tim!
