### ISSUE TITLE
Test flake in bstr.dart

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#416]
Hey @timsneath, this test is flaky: 
https://github.com/timsneath/win32/blob/cc9933f2216b5da247227a050aa3e2f21421abaf/test/bstr_test.dart#L23-L26

If you run this test several times on your computer, you will notice that it sometimes fails.

_Originally posted by @halildurmus in https://github.com/timsneath/win32/issues/406#issuecomment-1116141642_

**Comment by timsneath** [comment]
Yuck - that's annoying. How strange that it's intermittent. I'll take a look. 

The BSTR data type is documented here, for my ease of reference later:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/automat/bstr

**Comment by timsneath** [comment]
Doh! The clue is in my own comment: "A BSTR should end with a *word*-length null terminator."

And then I go and allocate a `DWORD`. 🤦

**Comment by halildurmus** [comment]
Oops 😂

**Comment by timsneath** [comment]
Should be fixed in 9bc07e40ee0035cbbab7bff9786e7d77fa09a046
