### ISSUE TITLE
Inheritance is broken for `WinRT` types

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#417]
I noticed this when trying to make async calls to `WinRT`. I believe this affects all `WinRT` types that extend a type other than `IInspectable`. e.g. `IAsyncOperation`(extends IAsyncInfo), `IStorageFile`(extends IStorageItem).

As of now, the generation script calculates `vtable` start index by iterating all of the interfaces that an interface extends and summing the number of methods in those interfaces: 
https://github.com/timsneath/win32/blob/dcec79e0d1d0de9fc1a8c1836ad1cd96ff7c9b72/tool/projection/com_interface.dart#L32-L34

With this calculation, `IAsyncOperation`'s vtable start index becomes `11` which I think it's wrong and I believe it should be `6`. The function should only iterate for `IInspectable` and `IUnknown` interfaces. 

The reason for that is I was looking into the header(.h) file for `Windows.Foundation` [here](https://raw.githubusercontent.com/tpn/winsdk-10/master/Include/10.0.16299.0/winrt/windows.foundation.h) and I found `IAsyncOperation`'s vtable:
```c
typedef struct __FIAsyncOperation_1_IInspectableVtbl
{
    BEGIN_INTERFACE
    HRESULT ( STDMETHODCALLTYPE *QueryInterface )(__RPC__in __FIAsyncOperation_1_IInspectable * This,
        /* [in] */ __RPC__in REFIID riid,
        /* [annotation][iid_is][out] */ 
        _COM_Outptr_  void **ppvObject);
    ULONG ( STDMETHODCALLTYPE *AddRef )(__RPC__in __FIAsyncOperation_1_IInspectable * This);
    ULONG ( STDMETHODCALLTYPE *Release )(__RPC__in __FIAsyncOperation_1_IInspectable * This);

    HRESULT ( STDMETHODCALLTYPE *GetIids )(__RPC__in __FIAsyncOperation_1_IInspectable * This,
        /* [out] */ __RPC__out ULONG *iidCount,
        /* [size_is][size_is][out] */ __RPC__deref_out_ecount_full_opt(*iidCount) IID **iids);
    HRESULT ( STDMETHODCALLTYPE *GetRuntimeClassName )(__RPC__in __FIAsyncOperation_1_IInspectable * This, /* [out] */ __RPC__deref_out_opt HSTRING *className);
    HRESULT ( STDMETHODCALLTYPE *GetTrustLevel )(__RPC__in __FIAsyncOperation_1_IInspectable * This, /* [out] */ __RPC__out TrustLevel *trustLevel);

    /* [propput] */ HRESULT ( STDMETHODCALLTYPE *put_Completed )(__RPC__in __FIAsyncOperation_1_IInspectable * This, /* [in] */ __RPC__in_opt __FIAsyncOperationCompletedHandler_1_IInspectable *handler);
    /* [propget] */ HRESULT ( STDMETHODCALLTYPE *get_Completed )(__RPC__in __FIAsyncOperation_1_IInspectable * This, /* [retval][out] */ __RPC__deref_out_opt __FIAsyncOperationCompletedHandler_1_IInspectable **handler);
    HRESULT ( STDMETHODCALLTYPE *GetResults )(__RPC__in __FIAsyncOperation_1_IInspectable * This, /* [retval][out] */ __RPC__out IInspectable * *results);
    END_INTERFACE
} __FIAsyncOperation_1_IInspectableVtbl;

interface __FIAsyncOperation_1_IInspectable
{
    CONST_VTBL struct __FIAsyncOperation_1_IInspectableVtbl *lpVtbl;
};
```
After I saw this, I changed the vtable start index to `6` in `IAsyncOperation` but it didn't work since `IAsyncInfo`'s vtable start index was also `6` and they used the same pointer. Then I had the idea to use `toInterface` helper method to get the `IAsyncInfo` with the correct pointer and it worked.

As a temporary workaround, I modified `IAsyncInfo.dart` like this:
```dart
  // This pointer is used in methods and properties instead of the `ptr` from
  // `IAsyncOperation`
  late final Pointer<COMObject> _ptr;

  // vtable begins at 6, is 5 entries long.
  IAsyncInfo(Pointer<COMObject> ptr, {required Allocator allocator})
      : super(ptr) {
    // We need to query IInspectable to get the proper pointer for IAsyncInfo.
    _ptr = toInterface(IID_IAsyncInfo, allocator: allocator);
  }
```
I don't like this workaround at all because it breaks the inheritance for `IAsyncInfo`. What I mean is, I send `ptr` parameter that comes from `IAsyncOperation` to `IInspectable` in `super(ptr)`. Because of that if we print the `runtimeClassName` property somewhere in `IAsyncInfo` it will output `Windows.Foundation.IAsyncOperation'1`. I'm worried that this will cause us some trouble as we use methods/properties from `IInspectable` and `IUnknown` in some places, especially inside `IVector` and `IVectorView`.

So far I haven't been able to find a way to fix this problem without breaking inheritance for both sides. You may have some thoughts about this.

If you want to check it out, my work on making async calls to WinRT is [here](https://github.com/halildurmus/win32/tree/async). Inside that, there is a simple working [example](https://github.com/halildurmus/win32/tree/async/example/winrt_picker) for `IFileOpenPicker`.

**Comment by timsneath** [comment]
Inheritance is a little confusing in WinRT -- I didn't understand it at first, and I know it's not fully modeled in the projection (I was focused at first on just getting the basics in place, one interface at a time).

As I understand it, every WinRT interface inherits from `IInspectable` (and nothing else). So the vtable should begin at 6 for all of them, including `IAsyncInfo` and `IAsyncOperation`. 

But WinRT interfaces can also "require" other interfaces. So when `IAsyncOperation` claims it implements `IAsyncInfo`, for example, that doesn't mean it inherits from it, it means that any object that supports `IAsyncOperation` must _also_ support the `IAsyncInfo` interface (through `QueryInterface`). And of course, some interfaces may require more than one interface to be implemented, for example [`IPropertySet`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ipropertyset?view=winrt-22000). 

My sense is that the best way to implement this in Dart might be through mixins, which allows Dart to idiomatically support this.

One note -- the `cacheVtableStart()` method for WinRT interfaces should be provided by `winrt_interface.dart`, which overrides the implementation listed above in `com_interface.dart`. That should return 6 for all these objects; I'll test and fix this if that's not the case.

Lastly, the best page I've found for information on all this is here: https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system#iinspectable-and-iunknown

**Comment by timsneath** [comment]
Commit 72eba9e910478bd33fb8dd8936132305d1d9422a addresses the incorrect calculation of vtable start for WinRT types.

**Comment by halildurmus** [comment]
> As I understand it, every WinRT interface inherits from `IInspectable` (and nothing else). So the vtable should begin at 6 for all of them, including `IAsyncInfo` and `IAsyncOperation`.

Right.

> But WinRT interfaces can also "require" other interfaces. So when `IAsyncOperation` claims it implements `IAsyncInfo`, for example, that doesn't mean it inherits from it, it means that any object that supports `IAsyncOperation` must _also_ support the `IAsyncInfo` interface (through `QueryInterface`). And of course, some interfaces may require more than one interface to be implemented, for example [`IPropertySet`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ipropertyset?view=winrt-22000).

Yes, it was very confusing at first but now I understand better how it works.

> My sense is that the best way to implement this in Dart might be through mixins, which allows Dart to idiomatically support this.

Using mixins might be a good idea. I'll investigate.

> Lastly, the best page I've found for information on all this is here: https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system#iinspectable-and-iunknown

Thanks, I'll check it out.

> Commit [72eba9e](https://github.com/timsneath/win32/commit/72eba9e910478bd33fb8dd8936132305d1d9422a) addresses the incorrect calculation of vtable start for WinRT types.

Thank you!

**Comment by timsneath** [comment]
Is there more we need to do to close this bug out?

**Comment by halildurmus** [comment]
> Is there more we need to do to close this bug out?

No, we can close this.
