### ISSUE TITLE
Windows Audio Session API (WASAPI) sample

### ISSUE THREAD

**Issue by postacik** [halildurmus/win32#421]
Hi,
It took quite some time to understand how to use the library for creating COM objects but I finally succeeded to create a demo application for WASAPI.

You can find the sample source code in the following [gist](https://gist.github.com/postacik/c1b8aa4d0c1abe9e877e33c44cd2ec47).

The sample plays a sine tone for 2 seconds.

I took this [gist](https://gist.github.com/mhamilt/859e57f064e4d5b2bb8e78ae55439d70) as a reference if you want to see the original C++ source code to find out how it's translated into dart.

I hope it would help others to go faster than me while creating their first win32 library.

@timsneath , can you please check if rules for creating and releasing objects in [this document](https://github.com/timsneath/win32/blob/main/doc/com.md) have been applied properly?

**Comment by timsneath** [comment]
Super! I'd love to add it as a sample to the example directory if you're willing for me to include it. If so, would you be willing to submit a pull request? I'll take a look at the code.

**Comment by postacik** [comment]
I submitted the pull request.

**Comment by timsneath** [comment]
Fixed in #422
