### ISSUE TITLE
MIDIINCAPS szPname problem

### ISSUE THREAD

**Issue by postacik** [halildurmus/win32#425]
Hi,
When I get a midiIn device properties using the midiInGetDevCaps function, szPname randomly comes back with extra characters at the end like the following:

Keystation 61 MK3Ǿ㧡搪Ǿ㨡搪Ǿ㩡搪Ǿ
MIDIIN2 (Keystation 61 MK3)콱掣Ǿ

However when I change the szPname function in structs.g.dart like the following, it comes back properly all the times:

```c
  String get szPname {
    final charCodes = <int>[];
    for (var i = 0; i < 32; i++) {
      charCodes.add(_szPname[i]);
      if (_szPname[i] == 0) break; //added this line
    }
    return String.fromCharCodes(charCodes);
  }

```

If this is the right way of fixing it, can you please fix the szPname functions in structs.g.dart?

**Comment by timsneath** [comment]
What a great catch! I think I've fixed this in the above commit (along with tests to make sure it doesn't regress). Thank you!
