### ISSUE TITLE
How to wait for an event handler in flutter

### ISSUE THREAD

**Issue by postacik** [halildurmus/win32#429]
Hi,
I use WASAPI functions to play audio buffers in a flutter application.

I initialize the IAudioClient with AUDCLNT_STREAMFLAGS_EVENTCALLBACK flag so that my code will be notified when the audio buffer is ready to feed.

The play loop is as the following:

```dart
    while (_isPlaying) {
      //final retval = WaitForSingleObject(_eventHandle!, 2000);
      if (!await waitForSingleObject(_eventHandle!)) {
        // Event handle timed out after a 2-second wait.
        _pAudioClient!.Stop();
        _isPlaying = false;
      } else {
        // See how much buffer space is available.
        _check(_pAudioClient!.GetCurrentPadding(pNumFramesPadding));
        final numFramesAvailable = bufferFrameCount - pNumFramesPadding.value;
        // Grab all the available space in the shared buffer.
        _check(_pAudioRenderClient!.GetBuffer(numFramesAvailable, pData));
        dataLoaded = loadDataCallback(numFramesAvailable, pData.value, _ppWaveFormat!.value.ref);
        _check(_pAudioRenderClient!.ReleaseBuffer(numFramesAvailable, dataLoaded ? 0 : AUDCLNT_BUFFERFLAGS.AUDCLNT_BUFFERFLAGS_SILENT));
      }
    }
```

If I call WaitForSingleObject function in the loop, my flutter application becomes responseless so I created the following stub function:

```dart
  Future<bool> waitForSingleObject(int handle) {
    return Future<bool>.delayed(const Duration(microseconds: 0), () {
      final retval = WaitForSingleObject(_eventHandle!, 2000);
      return (retval == 0);
    });
  }
```
Is this the right way of solving this problem?

**Comment by postacik** [comment]
Let me comment to my question

**Comment by postacik** [comment]
Let me comment to my own question:

Calling WaitForSingleObject in a loop, created unexpected problems in our Flutter application.

For example when we received asynchronous midi in events from a Windows plugin (https://github.com/postacik/music_lib_windows), Flutter user interface became unresponsive.

So we modified the loop as the following and had no problems thereafter:

```dart
    while (_isPlaying) {
      // Sleep for half the buffer duration.
      await Future.delayed(Duration(milliseconds: waitDuration));
      // See how much buffer space is available.
      _check(_pAudioClient!.GetCurrentPadding(pNumFramesPadding));
      final numFramesAvailable = bufferFrameCount - pNumFramesPadding.value;
      // Grab all the available space in the shared buffer.
      _check(_pAudioRenderClient!.GetBuffer(numFramesAvailable, pData));
      dataLoaded = loadDataCallback(numFramesAvailable, pData.value, _ppWaveFormat!.value.ref);
      _check(_pAudioRenderClient!.ReleaseBuffer(numFramesAvailable, dataLoaded ? 0 : AUDCLNT_BUFFERFLAGS.AUDCLNT_BUFFERFLAGS_SILENT));
    }
```

This was a really weird problem. 

I am sure someone who's an expert in both Windows and Flutter might tell why this happens.

**Comment by timsneath** [comment]
This is a bit out of my expertise, but I think `WaitForSingleObject` was essentially stalling the main Flutter UI thread. What you're doing now seems much better, using Dart primitives that allow the Flutter engine to continue to operate, possibly at the cost of more frequent polling.
