### ISSUE TITLE
Simplify using `WinRT` classes

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#431]
Created this issue to continue our discussion at https://github.com/timsneath/win32/issues/423.

> I love this. I wonder: as we're starting to it should be `Calendar()` rather than using the factory `Calendar.create()`. That feels more idiomatic. 

I agree. In that case, we could generate activatable `WinRT` classes this way:
```dart
class Calendar extends IInspectable with ICalendar, ITimeZoneOnCalendar {
  Calendar() : super(ActivateWinRTClass('Windows.Globalization.Calendar'));

  Calendar.fromPointer(super.ptr);
}
```

> That will cause a cascading breaking change for traditional COM interfaces though, and I'm not sure how to get around that. Perhaps they need to become factory constructors themselves, with `IFileOpenDialog.cast(myComObject)` or something. We should probably move this dialog into a separate design doc 

Yeah, this will be difficult to do for COM interfaces.

> In the meantime, I'm going to merge this, since it's obviously in the same vein as `trustLevel` and `runtimeClassName`. Maybe we'll hide these from the "outside world" later on. It looks like that's what C# does.

Hiding them might be a good idea. Looks like [C#/WinRT](https://github.com/microsoft/CsWinRT/blob/master/src/WinRT.Runtime/IInspectable.cs#L135-L156) only exposes `GetRuntimeClassName` method to consumers.

**Comment by timsneath** [comment]
@halildurmus Hey there! I've been busy refactoring the generator classes (again!) 

I think where I've come to is more maintainable in the long-term, and allows for things like WinRT parameters that require set up and teardown. Let me know if this causes you pain with any work that is midstream, and I'll help you migrate code forward.

**Comment by halildurmus** [comment]
> @halildurmus Hey there! I've been busy refactoring the generator classes (again!)

> I think where I've come to is more maintainable in the long-term, and allows for things like WinRT parameters that require set up and teardown. 

I LOVE what you did with the generator, it's so much cleaner now. Thank you!

> Let me know if this causes you pain with any work that is midstream, and I'll help you migrate code forward.

I'm not working on this at the moment. I was busy adding support for asynchronous WinRT APIs and IMap & IMapView and I'm almost done with them. This won't cause me much trouble, I just need to resolve merge conflicts.

But there is something else you can help me with. It's about making memory management easier for consumers (and us 😄). I'll write a detailed explanation on the subject tomorrow.

**Comment by timsneath** [comment]
Thank you! 

I also created a branch to experiment with the mixin model outlined here. Take a look at PhoneNumberFormatter (https://github.com/timsneath/win32/blob/phoneNumberFormatter/lib/src/winrt/phonenumberformatter.dart) and see what you think?

**Comment by halildurmus** [comment]
Nice! I have one suggestion though.

In the static methods, you can use `CreateActivationFactory` helper method to create pointers to `XXStatics` classes.

**Comment by halildurmus** [comment]
Curious, are you planning to project factory constructors as well? If I remember correctly, PhoneNumberFormatter doesn't have any factory constructors but Calendar does.

**Comment by timsneath** [comment]
Great tip to use `CreateActivationFactory`! Thank you. Updated. Yeah, we should do factory constructors too... 

I'm so enjoying having a _real_ developer watching over my shoulder: thank you :)

**Comment by halildurmus** [comment]
> I'm so enjoying having a _real_ developer watching over my shoulder: thank you :)

Thank you :) I'm learning a lot from you.

Now I'd like to explain the memory management thing I mentioned yesterday. I'll assume that we're using the `Mixin` model for generating WinRT classes.

There are some cases where we can't deallocate pointers in the generated code. Therefore, it is the consumers' responsibility to deallocate them once they're done using them.

These are:
- WinRT class pointers e.g. `Calendar`'s pointer (these pointers are allocated by constructors such as `Calendar`'s default constructor, factory constructors, methods, properties, or by consumers using `ActivateObject` or other helper methods)
- WinRT mixin pointers e.g. pointers of the `ICalendar` and `ITimeZoneOnCalendar`
- APIs that return `IVector<T extends IInspectable>` or `IVectorView<T extends IInspectable>` e.g. `IVector<StorageFile>`. As of now, these are exposed as `Pointer<COMObject>`. We only auto-generate APIs that return `IVector<String>` and `IVectorView<String>` at the moment but we will add support for these in the future. [Here](https://github.com/timsneath/win32/blob/main/lib/src/winrt/inetworkinformationstatics.dart#L122-L155) is the one I manually generated. 

...and probably much more in the future as the WinRT projection matures (asynchronous APIs, IMap & IMapView...).

The problem is that there are many situations where the consumers need to free pointers manually and I think it is pretty common to forget freeing some of the pointers (especially if you're using a lot of them). Another thing that is quite painful to deal with is that if you accidentally call `free` method twice on the same pointer, the process will crash and good luck figuring out the source of the problem (I got bitten by this many times :( ).

I've been trying to find a way to fix these issues for the past few days and I have some ideas I'd like to share with you.

I'll start with the first design. We could consider introducing a class that manages the pointers that could not be freed in the generated code:
```dart
class WinRTAllocator {
  static final allocator = Arena();

  /// Releases all resources managed by the [allocator].
  static void freeAll() => allocator.releaseAll(reuse: true);
}
```

This class would contain a `static` allocator to be used by the generated code and a static method to free all pointers. We would expose this to the outside world so that the consumers would have a way of freeing all pointers by calling just a single method once they're done using WinRT APIs.

Here are the cases where we need to modify the generator to use this allocator:
- WinRT class pointers
- WinRT mixin pointers (We would pass `WinRTAllocator.allocator` to `toInterface` method as a parameter)
- APIs that return `IVector<T extends IInspectable>` or `IVectorView<T extends IInspectable>`

...and much more in the future...

This design is much simpler to use, but if consumers use WinRT APIs heavily, I'm worried that the memory usage may be higher until they call `WinRTAllocator.freeAll()` (there may be some cases where the consumer is using tightly coupled APIs and because of this they can't call `freeAll` method between calls and must wait for all calls to complete). 

To solve this, here is the final design I came up with. First, we could create our own `Arena` implementation by slightly modifying `dart:ffi`'s implementation to allow freeing specific pointers from the `_managedMemoryPointers` list (by modifying `Arena`'s `free` method):
```dart
class WinRTAllocator {
  static final allocator = _Arena();

  /// Releases memory allocated on the native heap.
  static void free(Pointer<NativeType> pointer) => allocator.free(pointer);

  /// Releases all resources managed by the [allocator].
  static void freeAll() => allocator.releaseAll(reuse: true);
}

class _Arena implements Allocator {
  /// The [Allocator] used for allocation and freeing.
  final Allocator _wrappedAllocator;

  /// Native memory under management by this [Arena].
  final List<Pointer<NativeType>> _managedMemoryPointers = [];

  /// Callbacks for releasing native resources under management by this [Arena].
  final List<void Function()> _managedResourceReleaseCallbacks = [];

  bool _inUse = true;

  /// Creates a arena of allocations.
  ///
  /// The [allocator] is used to do the actual allocation and freeing of
  /// memory. It defaults to using [calloc].
  _Arena([Allocator allocator = calloc]) : _wrappedAllocator = allocator;

  /// Allocates memory and includes it in the arena.
  ///
  /// Uses the allocator provided to the [Arena] constructor to do the
  /// allocation.
  ///
  /// Throws an [ArgumentError] if the number of bytes or alignment cannot be
  /// satisfied.
  @override
  Pointer<T> allocate<T extends NativeType>(int byteCount, {int? alignment}) {
    _ensureInUse();
    final p = _wrappedAllocator.allocate<T>(byteCount, alignment: alignment);
    _managedMemoryPointers.add(p);
    return p;
  }

  /// Registers [resource] in this arena.
  ///
  /// Executes [releaseCallback] on [releaseAll].
  ///
  /// Returns [resource] again, to allow for easily inserting
  /// `arena.using(resource, ...)` where the resource is allocated.
  T using<T>(T resource, void Function(T) releaseCallback) {
    _ensureInUse();
    releaseCallback = Zone.current.bindUnaryCallback(releaseCallback);
    _managedResourceReleaseCallbacks.add(() => releaseCallback(resource));
    return resource;
  }

  /// Registers [releaseResourceCallback] to be executed on [releaseAll].
  void onReleaseAll(void Function() releaseResourceCallback) {
    _managedResourceReleaseCallbacks.add(releaseResourceCallback);
  }

  /// Releases all resources that this [Arena] manages.
  ///
  /// If [reuse] is `true`, the arena can be used again after resources
  /// have been released. If not, the default, then the [allocate]
  /// and [using] methods must not be called after a call to `releaseAll`.
  ///
  /// If any of the callbacks throw, [releaseAll] is interrupted, and should
  /// be started again.
  void releaseAll({bool reuse = false}) {
    if (!reuse) {
      _inUse = false;
    }
    // The code below is deliberately wirtten to allow allocations to happen
    // during `releaseAll(reuse:true)`. The arena will still be guaranteed
    // empty when the `releaseAll` call returns.
    while (_managedResourceReleaseCallbacks.isNotEmpty) {
      _managedResourceReleaseCallbacks.removeLast()();
    }
    for (final p in _managedMemoryPointers) {
      _wrappedAllocator.free(p);
    }
    _managedMemoryPointers.clear();
  }

  /// Releases memory allocated on the native heap.
  @override
  void free(Pointer<NativeType> pointer) {
    final isRemoved = _managedMemoryPointers.remove(pointer);
    if (isRemoved) _wrappedAllocator.free(pointer);
  }

  void _ensureInUse() {
    if (!_inUse) {
      throw StateError(
          'Arena no longer in use, `releaseAll(reuse: false)` was called.');
    }
  }
}
```

(I'd like to point out that calling `WinRTAllocator`'s `free` multiple times on the same pointer won't crash your process as the implementation checks if the pointer exists in the `_managedMemoryPointers` list before calling the native API.)

Then, we could create a `dispose` method in `IInspectable`:
```dart
class IInspectable extends IUnknown {
  ...

  /// Releases all memory allocated by this object.
  void dispose() => WinRTAllocator.free(ptr);
}
```

...and modify WinRT classes and mixins like this:
```dart
// icalendar.dart
mixin ICalendar on IInspectable {
  late final ptrICalendar =
      toInterface(IID_ICalendar, allocator: WinRTAllocator.allocator);
  // ...
}

// itimezoneoncalendar.dart
mixin ITimeZoneOnCalendar on IInspectable {
  late final ptrITimeZoneOnCalendar =
      toInterface(IID_ITimeZoneOnCalendar, allocator: WinRTAllocator.allocator);
  // ...
}

// calendar.dart
class Calendar extends IInspectable with ICalendar, ITimeZoneOnCalendar {
  Calendar() : super(ActivateWinRTClass(_className));
  Calendar.fromPointer(super.ptr);

  static const _className = 'Windows.Globalization.Calendar';

  // ...

  @override
  void dispose() {
    WinRTAllocator.free(ptr);
    WinRTAllocator.free(ptrICalendar);
    WinRTAllocator.free(ptrITimeZoneOnCalendar);
  }
}
```

With this design, consumers have the flexibility to use the `dispose` method of the WinRT classes in combination with the `freeAll` method of the `WinRTAllocator` for memory management. They can decide which option is more suitable for their needs or preferences. Some might prefer to just use `freeAll` for its simplicity while others may use both of them to make their applications more efficient.

Looking forward to your thoughts on this.

**Comment by timsneath** [comment]
Moving the memory management design conversation to a separate issue (thank you -- I'll get back to you on this.)

In the meantime, here's the updated Calendar object, per the design above:
https://github.com/timsneath/win32/blob/winrt-mixins/lib/src/winrt/calendar.dart

**Comment by timsneath** [comment]
Closing now that we've settled on a design. Fixed in https://github.com/timsneath/win32/pull/442.
