### ISSUE TITLE
[Request] GetVolumeInformationW and SetErrorMode

### ISSUE THREAD

**Issue by cbenhagen** [halildurmus/win32#458]
Can you please add [GetVolumeInformationW](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumeinformationw)? It would be nice if  also [SetErrorMode](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-seterrormode) could be added to [prevent the system of asking to user to insert a floppy or cdrom](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumeinformationw#remarks).

**Comment by timsneath** [comment]
Of course. Added #462

**Comment by cbenhagen** [comment]
Awesome!
