### ISSUE TITLE
Consider converting WinRT Interface constructors to named ones

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#464]
I'm about to modify the generator to support projecting `IVector<T extends IInspectable>` (and `IVectorView`) types (we only project `String` ones at the moment) and also project async APIs as `Future`. 

Now, in order to do that, I need to use the `creator` parameter from the `IVector`, `IVectorView` (and `IAsyncOperation`). This parameter takes a constructor and allows us to create constructors from generic types. 

The problem is that since WinRT classes and WinRT interfaces don't have matching named constructors (WinRT classes have `.fromPointer` while WinRT interfaces only have a default constructor) at the moment, I have to find the correct constructor to use, perhaps by checking if the type is `Class` or `Interface` but it might reduce the readability of the code as some of the APIs returns nested types. For example, [pickMultipleFilesAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.pickmultiplefilesasync) returns `IAsyncOperation<IVectorView<StorageFile>>` which I need to use `two` `creator` parameters (for IVectorView and StorageFile) inside the projection. so I'd rather not do that.

We have a couple of options:
- Convert default constructors of WinRT Interfaces to named ones (`.fromPointer`) to match with WinRT Classes (we could also rename both of them to `.from` to make it shorter)
- Don't remove the default constructors of WinRT Interfaces, instead, add a named one (`.fromPointer`)

Personally, I'm leaning towards the first option. What do you think?

**Comment by timsneath** [comment]
AWESOME! Can't wait for async APIs.

Yeah, I think I agree. Interfaces shouldn't be constructable objects; classes can be created and cast to interfaces. It's beneficial to keep close to other WinRT / COM mappings. 

Where I struggle is how this maps to COM. Should COM interfaces also use `.from`, rather than having a default constructor? It would be useful to try this out and see how it plays out for something like https://github.com/timsneath/win32/blob/c516101d8e98fd6cc7c2bac62560e09cc1628ccf/example/com_demo.dart

**Comment by halildurmus** [comment]
> Where I struggle is how this maps to COM. Should COM interfaces also use .from, rather than having a default constructor? It would be useful to try this out and see how it plays out for something like https://github.com/timsneath/win32/blob/c516101d8e98fd6cc7c2bac62560e09cc1628ccf/example/com_demo.dart

I looked into this a while ago but couldn't figure it out (COM is so confusing). I might take a look at it again sometime.
