### ISSUE TITLE
[Request] Add more IOCTL related constants / structs 

### ISSUE THREAD

**Issue by cbenhagen** [halildurmus/win32#468]
May I kindly ask you to add some more IOCTL related constants / structs? Most importantly:

- [IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-ioctl_volume_get_volume_disk_extents)
- [VOLUME_DISK_EXTENTS](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-volume_disk_extents)
- [STORAGE_DEVICE_NUMBER](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-storage_device_number)

Thank you very much in advance!

**Comment by timsneath** [comment]
Of course! Just added a pull request for these. Also feel free to submit a pull request for others you may need. 

Constants like this go here:
https://github.com/timsneath/win32/blob/main/lib/src/constants_nodoc.dart#L2845

Structs go here (with doc comment drawn from docs.microsoft.com):
https://github.com/timsneath/win32/blob/main/tool/generator/lib/src/inputs/structs.dart

Pull request #472 gives you a good template for any others you may need to add.
