### ISSUE TITLE
Static get properties are incorrectly projected in WinRT classes

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#474]
For example, in the `Gamepad` class, `IGamepadStatics`'s `Gamepads` property is projected as:
```dart
  static Pointer<COMObject> get_Gamepads() {
    final activationFactory =
        CreateActivationFactory(_className, IID_IGamepadStatics);

    try {
      final result = IGamepadStatics(activationFactory).get_Gamepads();
      return result;
    } finally {
      free(activationFactory);
    }
  }
```

Instead, it should be projected as:
```dart
  static List<String> get Gamepads {
    final activationFactory =
        CreateActivationFactory(_className, IID_IGamepadStatics);

    try {
      final result = IGamepadStatics(activationFactory).Gamepads;
      return result;
    } finally {
      free(activationFactory);
    }
  }
```

Relevant code: https://github.com/timsneath/win32/blob/bee7a29a0ca11fc28add20dfd4493180a2f8b233/tool/generator/lib/src/projection/winrt_class.dart#L106-L127

**Comment by timsneath** [comment]
Oh goodness! It's layers upon layers upon layers, isn't it! Good spot -- thanks for catching this.

**Comment by halildurmus** [comment]
> Oh goodness! It's layers upon layers upon layers, isn't it!

It definitely is 😃.

> Good spot -- thanks for catching this.

Thanks. I created #475 to fix this.
