### ISSUE TITLE
Resolve naming conflicts in the `FileOpenPicker` class

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#477]
`IFileOpenPicker`'s [pickSingleFileAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.picksinglefileasync?view=winrt-22621#windows-storage-pickers-fileopenpicker-picksinglefileasync) conflicts with `IFileOpenPickerWithOperationId`'s [pickSingleFileAsync(string pickerOperationId)](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.picksinglefileasync?view=winrt-22621#windows-storage-pickers-fileopenpicker-picksinglefileasync(system-string)).

**Comment by timsneath** [comment]
Ugh -- they're supposed to provide a `Windows.Foundation.Metadata.OverloadAttribute` for this reason (languages that don't include method overloading in their design). I wonder if this is an outlier? We may have to manually provide a list of overrides like this, or build some heuristic.

**Comment by halildurmus** [comment]
I found another naming conflict in the [DecimalFormatter](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.decimalformatter?view=winrt-22621) class. `DecimalFormatter` inherits from [INumberFormatter](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.inumberformatter?view=winrt-22621) and [INumberFormatter2](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.inumberformatter2?view=winrt-22621) interfaces.

`INumberFormatter` has overloaded `Format` methods to format several data types whereas `INumberFormatter2` has distinct format methods to format several data types:
<p align="center">
    <img src="https://user-images.githubusercontent.com/45524029/188312500-b0a77593-87f3-4b1e-9f02-32a21bc6737d.png">
    <img src="https://user-images.githubusercontent.com/45524029/188312506-66b7db4e-c66a-47db-a7f9-3ec492799140.png">
</p>

Since the functionality provided by these methods is the same, we can exclude the `INumberFormatter2` interface in the generator.

As for the conflict in the `FileOpenPicker` class, the documentation of [pickSingleFileAsync(string pickerOperationId)](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.picksinglefileasync?view=winrt-22621#windows-storage-pickers-fileopenpicker-picksinglefileasync(system-string)) says:
> pickerOperationId [String](https://docs.microsoft.com/en-us/dotnet/api/system.string) 
   This argument is ignored and has no effect.

Because of that, I think we should also exclude the `IFileOperationWithOperationId` interface.

I created #555 for this. WDYT?
