### ISSUE TITLE
Support generic collections in `implementsMappers`

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#480]
Noticed this while working on #479. Take `IXmlNodeList` for example. It requires two interfaces: `IVectorView<IXmlNode>` and `IIterable<IXmlNode>`.

The problem is that the `typeDef` of these interfaces returns an empty `name`. This is breaking a lot of things, as we rely heavily on `typeDef.name` for `classDeclaration` and `implementsMappers`.  I ignored them for now in #479.

In order to get the names of these types, we can call typeDef like this:
```dart
print(typeDef.interfaces.first.typeSpec?.type?.name); // Prints Windows.Foundation.Collections.IVectorView`1
print(typeDef.interfaces.first.typeSpec?.typeArg?.name); // Prints Windows.Data.Xml.Dom.IXmlNode
```
The difficulty is that these types can be nested and/or has multiple `typeArg`s (e.g. `IVectorView<IMapView<String, Object>>`, `IMap<String, IVector<String>>`).

In a couple of days, I'll continue my work on #465. In that, I'll have to modify the generator to expose `Pointer<COMObject>` types to their respective types (e.g. IFileOpenPicker's `pickMultipleFilesAsync()` will be exposed as `Future<List<StorageFile>?>` instead of `Pointer<COMObject>` or Calendar's `Clone()` will return `Calendar`). This will probably help to support this as well.

**Comment by timsneath** [comment]
Yeah, I've been puzzling over how to represent generics for a while from the winmd side. The code isn't super clean there, mostly because WinMD is a spidery mess of circular type references. 

What would you _like_ to see represented? I could give you one big blob like `IMap<String, IVector<String>>`, but all that does is push the parsing work to the generator. I'll make the changes on the winmd side as needed.

**Comment by halildurmus** [comment]
I was thinking of writing a function that returns a String like `IMap<String, IVector<String>` by parsing the `TypeDef`. I'll look into this tomorrow and share my progress.

EDIT: Thank you for the invitation :)

**Comment by timsneath** [comment]
That's easy enough -- but is that String useful from a mapping perspective? Or do you then need to decompose it again? I'd like to give you what you need from the first!

**Comment by halildurmus** [comment]
I won't know until I dig deeper into this tomorrow. Hopefully, I won't need to decompose it again.
