### ISSUE TITLE
Feature Request: Add IP Helper API for controlling network interfaces

### ISSUE THREAD

**Issue by point-source** [halildurmus/win32#485]
I am trying to write an application which can view the current settings of network interfaces and modify them based on a database and set of rules. I was hoping to use this library to do so rather than issuing commands to shell via process but it seems this library does not yet include the [IP Helper API](https://docs.microsoft.com/en-us/windows/win32/api/_iphlp/). Would it be possible to support this in the future?

Edit for clarity: I looked through the NetworkListManager api that is part of this library and it appears to only deal with networks (logical) rather than network interfaces (physical).

**Comment by timsneath** [comment]
Sure, I can take a look at that. Is there a subset of APIs here that are necessary?

**Comment by point-source** [comment]
Mostly trying to get:

-mac address
-current ip address, if any
-subnet mask
-gateway

And trying to set:

-interface name
-current ip address, if any
-subnet mask
-gateway

**Comment by timsneath** [comment]
Thanks. Do you know which APIs specifically you need implemented? Sorry to be a pest -- it's just that there are a lot of APIs in this category, and it's probably not worth adding all of them to win32, since some are quite esoteric.

**Comment by point-source** [comment]
> Thanks. Do you know which APIs specifically you need implemented? Sorry to be a pest -- it's just that there are a lot of APIs in this category, and it's probably not worth adding all of them to win32, since some are quite esoteric.

Not at all! My apologies. Let me do some more research and get the specific ones. Thanks for the help

**Comment by point-source** [comment]
Here are the ones that appear to be necessary at first glance:

- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-addipaddress
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-deleteipaddress
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadapterindex
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersinfo
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getinterfaceinfo
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getperadapterinfo
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-ipreleaseaddress
- https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-iprenewaddress

**Comment by point-source** [comment]
Woah! That was unbelievably fast. Thanks! Where's the donate button?
