### ISSUE TITLE
Support Sensor API

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#494]
Here is the [link](https://docs.microsoft.com/en-us/windows/win32/api/_winsensors/) that lists all the enums, functions, and interfaces of the `Sensor API`.

### Discussed in https://github.com/timsneath/win32/discussions/493

<div type='discussions-op-text'>

<sup>Originally posted by **GiuseppeFn** June 10, 2022</sup>
I really hate to ask dumb questions... But I really can't find it
I was trying a simple snippet from msdn
```
var hr = CoCreateInstance(CLSID_SensorManager, 
                        nullptr, CLSCTX_, INPROC_SERVER,
                        IID_PPV_ARGS(&pSensorManager));

if(hr == HRESULT_FROM_WIN32(ERROR_ACCESS_DISABLED_BY_POLICY)){}
```
The CLSID_SensorManager GUID doesn't seem to be there at all.

Does this library supports windows sensors?</div>

**Comment by timsneath** [comment]
Hi @GiuseppeFn, I've created a branch with this in: 
https://github.com/timsneath/win32/tree/sensors

I don't think I have any sensors on my machine though... so I haven't been able to test it directly.
