### ISSUE TITLE
Help me convert GetAltTabInfoA function to dart

### ISSUE THREAD

**Issue by Far-Se** [halildurmus/win32#499]
Hello, I need this function to see if the window is on current Desktop/Workspace/Screen and not hidden or other Workspace. 
EnumWindows show all windows and GetWindowInfo isn't helpful enough.
Link to function docs:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getalttabinfoa
Structure;
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-alttabinfo

Code that I tried but didn't work:
```dart

class ALTTABINFO extends Struct {
  @Uint32()
  external int cbSize;
  @UintPtr()
  external int cItems;
  @UintPtr()
  external int cColumns;
  @UintPtr()
  external int cRows;
  @UintPtr()
  external int iColFocus;
  @UintPtr()
  external int iRowFocus;
  @UintPtr()
  external int cxItem;
  @UintPtr()
  external int cyItem;

  external POINT ptStart;
}

final _user32 = DynamicLibrary.open('user32.dll');

int GetAltTabInfo(int hwnd, int iItem, Pointer<ALTTABINFO> pati,
        Pointer<Int16> psczItemText, int cchItemText) =>
    _GetAltTabInfo(hwnd, iItem, pati, psczItemText, cchItemText);

final _GetAltTabInfo = _user32.lookupFunction<
    Int32 Function(IntPtr hwnd, Uint32 uIDItem, Pointer<ALTTABINFO> lpString,
        Pointer<Int16> psczItemText, Uint32 cchItemText),
    int Function(int hwnd, int uIDItem, Pointer<ALTTABINFO> lpString,
        Pointer<Int16> psczItemText, int cchItemText)>('GetAltTabInfoA');

```
In theory it should return true if hWnd is on AltTab Menu.

**Comment by timsneath** [comment]
You'll need `GetAltTabInfoW`. I think that might be your only mistake. (The `A` suffix represents ASCII, which requires 8-bit characters). Look at `functions.json` for examples of how to define a new API, and then run `tools\generate.cmd` to auto create it.

**Comment by Far-Se** [comment]
@timsneath Thanks for the response.
I've tried with W as well and it didn't worked. 
Didn't knew there is a generator, that is what I get for not reading the documentation :)
However, I've found a solution to see current windows on active Workspace:
```dart
  final cloaked = calloc<Int>();
  DwmGetWindowAttribute(hWnd, DWMWINDOWATTRIBUTE.DWMWA_CLOAKED, cloaked, sizeOf<Int>());
```
[link with cloaked values](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute#:~:text=is%20not%20supported.-,DWMWA_CLOAKED,-Use%20with%20DwmGetWindowAttribute), 0 is active/visible.
