### ISSUE TITLE
SendInput by multiple keys

### ISSUE THREAD

**Issue by fathah** [halildurmus/win32#536]
Thanks for this wonderful package.

I could implement the single key click using `SendInput` . Is there a way to perform Ctrl clicks like `Ctrl+C` to copy and `Ctrl+V` for pasting.

Thanks

**Comment by Far-Se** [comment]
Here: https://github.com/Far-Se/tabame/blob/master/lib/models/keys.dart

To send ctrl+c use `WinKeys.send("{#CTRL}C");`

**Comment by fathah** [comment]
@Far-Se thanks  ❤️
