### ISSUE TITLE
Getting the real background-color 

### ISSUE THREAD

**Issue by farukx** [halildurmus/win32#55]
hi can you help me 

this  is method fails, return value 0

```
void showBg() {
   var hr = CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
  if (FAILED(hr)) {
    throw WindowsException(hr);
  }

  final bgColor = DesktopWallpaper.createInstance();
  final nlmBackgroundColor = allocate<Uint32>();
  hr = bgColor.GetBackgroundColor(nlmBackgroundColor);
  
  if (FAILED(hr)) {
    throw WindowsException(hr);
  }

  final connectivity = nlmBackgroundColor.value;

  print(connectivity);
  free(nlmBackgroundColor);
  free(bgColor.ptr);


}
```

**Comment by timsneath** [comment]
Returning 0 would be expected if you have an RGB(0,0,0) color for your desktop. If `hr` returns `S_OK`, then the method succeeded. On my machine, your snippet correctly prints 6318152, which is RGB(72, 104, 96). 

I've [created a sample](https://github.com/timsneath/win32/blob/master/example/wallpaper.dart) that extends your code snippet a little. On my machine, running this sample shows:
```
[C:\src\win32] dart example\wallpaper.dart
Wallpaper path is: c:\windows\web\wallpaper\windows\img0.jpg
Background color is: RGB(72, 104, 96)
```

Oh, and don't forget to call `CoUninitialize()` at the end of your method to close COM properly!

Hope this helps!

**Comment by farukx** [comment]
gratefully thanks
