### ISSUE TITLE
Support CryptProtectData, CryptUnprotectData, etc. from `dpapi.h`

### ISSUE THREAD

**Issue by Jordan-Nelson** [halildurmus/win32#554]
### Request
Support APIs from [dpapi.h](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/):
- [CryptProtectData](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata)
- [CryptProtectMemory](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectmemory)
- [CryptUnprotectData](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptunprotectdata)
- [CryptUnprotectMemory](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptunprotectmemory)
- [CryptUpdateProtectedState](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptupdateprotectedstate)

I can look into opening a PR to add the bindings if there are no reservations with them being added to this lib.

**Comment by timsneath** [comment]
Great! Yes please!
