### ISSUE TITLE
How to Control the Brightness of Monitor

### ISSUE THREAD

**Issue by farukx** [halildurmus/win32#56]
How do I Adjust the Brightness or Contrast can you help me pls @timsneath

**Comment by timsneath** [comment]
You mean *monitor* brightness and contrast, @farukx? Can you tell me more about your scenario?

**Comment by farukx** [comment]
setting minimum, maximum, and current brightness settings manuel. API call to change brightness of physical monitors https://docs.microsoft.com/en-us/windows/win32/api/highlevelmonitorconfigurationapi/

**Comment by timsneath** [comment]
Got it! Just curious to understand how you plan to use these features?

**Comment by farukx** [comment]
(I know less english) my future plan simple manually changing the screen brightness to desktop app 
![brightness](https://user-images.githubusercontent.com/55917247/86443934-a6970000-bd18-11ea-801f-bb9073254101.png)

**Comment by timsneath** [comment]
You should find this supported now. There's a comprehensive example at https://github.com/timsneath/win32/blob/master/example/monitor.dart

**Comment by farukx** [comment]
Thank you very much!
