### ISSUE TITLE
ReadProcessMemory

### ISSUE THREAD

**Issue by EdwinLam** [halildurmus/win32#579]
hello,Can you write an example of ReadProcessMemory? I don't know how to handle the garbled data returned by ` final lpNumberOfBytesRead = calloc<IntPtr>();
    final lpBuffer = wsalloc(byte);
    SetLastError(0);
    ReadProcessMemory(hProcess, Pointer.fromAddress(lpBaseAddress), lpBuffer,
        byte, lpNumberOfBytesRead);`

**Comment by timsneath** [comment]
Unfortunately I don't have the bandwidth to document all the Win32 APIs.

But if you can show me a simple permissively licensed example written in C, ideally from the Microsoft docs, I'll see if I can convert it for you.

**Comment by EdwinLam** [comment]
> Unfortunately I don't have the bandwidth to document all the Win32 APIs.
> 
> But if you can show me a simple permissively licensed example written in C, ideally from the Microsoft docs, I'll see if I can convert it for you.

thx~

**Comment by bdangvnt** [comment]
I'm Interested
