### ISSUE TITLE
Screen size in px

### ISSUE THREAD

**Issue by pixltd-dev** [halildurmus/win32#585]
Hi, can I somehow use win32 to get screen / virtual screen (all monitors) resolution? I've seen here the physical (mm) size part, but maybe I just missed it if it's here somewhere, but I need just px resolution. So far I have been able to only get the window px size.

Thank you

**Comment by halildurmus** [comment]
If you only want the resolution of the primary monitor, you can use [GetSystemMetrics](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics) API.

Here is a simple example:
```dart
import 'package:win32/win32.dart';

void main() {
  final screenWidth = GetSystemMetrics(SM_CXFULLSCREEN);
  final screenHeight = GetSystemMetrics(SM_CYFULLSCREEN);
  print(
      'The width of the client area for a full-screen window on the primary display monitor: $screenWidth');
  print(
      'The height of the client area for a full-screen window on the primary display monitor: $screenHeight');

  final virtualScreenWidth = GetSystemMetrics(SM_CXVIRTUALSCREEN);
  final virtualScreenHeight = GetSystemMetrics(SM_CYVIRTUALSCREEN);
  print('The width of the virtual screen: $virtualScreenWidth');
  print('The height of the virtual screen: $virtualScreenHeight');
}
```

**Comment by pixltd-dev** [comment]
> If you only want the resolution of the primary monitor, you can use [GetSystemMetrics](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics) API.
> 
> Here is a simple example:
> 
> ```dart
> import 'package:win32/win32.dart';
> 
> void main() {
>   final screenWidth = GetSystemMetrics(SM_CXFULLSCREEN);
>   final screenHeight = GetSystemMetrics(SM_CYFULLSCREEN);
>   print(
>       'The width of the client area for a full-screen window on the primary display monitor: $screenWidth');
>   print(
>       'The height of the client area for a full-screen window on the primary display monitor: $screenHeight');
> 
>   final virtualScreenWidth = GetSystemMetrics(SM_CXVIRTUALSCREEN);
>   final virtualScreenHeight = GetSystemMetrics(SM_CYVIRTUALSCREEN);
>   print('The width of the virtual screen: $virtualScreenWidth');
>   print('The height of the virtual screen: $virtualScreenHeight');
> }
> ```

Thank youu!

**Comment by halildurmus** [comment]
It seems that if `DPI` scaling level is set to more than `100%` in your Windows, `GetSystemMetrics` may return incorrect values. 
Because of that, I would recommend you to call `SetProcessDpiAwarenessContext` API before calling `GetSystemMetrics`:
```dart
import 'package:win32/win32.dart';

void main() {
  SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

  final screenWidth = GetSystemMetrics(SM_CXFULLSCREEN);
  final screenHeight = GetSystemMetrics(SM_CYFULLSCREEN);
  print(
      'The width of the client area for a full-screen window on the primary display monitor: $screenWidth');
  print(
      'The height of the client area for a full-screen window on the primary display monitor: $screenHeight');

  final virtualScreenWidth = GetSystemMetrics(SM_CXVIRTUALSCREEN);
  final virtualScreenHeight = GetSystemMetrics(SM_CYVIRTUALSCREEN);
  print('The width of the virtual screen: $virtualScreenWidth');
  print('The height of the virtual screen: $virtualScreenHeight');
}
```

**Comment by pixltd-dev** [comment]
Thank you, seems to be exactly what I needed!
