### ISSUE TITLE
Broken API reference documentation on v3.1.0

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#589]
It looks like `dartdoc` couldn't generate [API reference documentation](https://pub.dev/documentation/win32/latest/) for latest version.

You can see the logs at https://pub.dev/documentation/win32/latest/log.txt

> STDERR:
Unhandled exception:
In categories definition for shcore, "markdown" resolves to the missing file /tmp/pub-dartlang-dartdocLWPHAS/pkg/doc/shcore.md

`/doc/kernelbase.md` and `/doc/shcore.md` files were deleted in #580 but it looks like there are still references to them in: https://github.com/timsneath/win32/blob/1a1239d5f69a506606bbd2c085d8667db31715ba/dartdoc_options.yaml#L35-L36

@timsneath I _think_ these should be removed but I'm not sure.

**Comment by timsneath** [comment]
Yeah I saw that. Gonna have to add a test for that. Will also file an issue on dartdoc, since it shouldn't bail on something so trivial.
