### ISSUE TITLE
Please add bluetooth example for discover, connect and write using win32 socket 

### ISSUE THREAD

**Issue by ekokurniadi** [halildurmus/win32#641]
Hello, Thank you for created this package, is realy helpfull, but i have a problem with bluetooth connection on flutter desktop windows. Could you mind to create a some example for handle bluetooth rfcomm on this package please ?

**Comment by timsneath** [comment]
I'm sorry -- that's a lot of work you're asking of me. 

If there's a simple C example out there that you need help converting, then I'll see if I can help, but realistically I don't have time to write example code on demand. This project is aimed primarily at existing Windows developers who know how to write something in C but are looking for Dart language bindings.
