### ISSUE TITLE
Methods/properties that return WinRT objects should be nullable

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#647]
For example, [NetworkInformation.GetInternetConnectionProfile Method](https://learn.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkinformation.getinternetconnectionprofile?view=winrt-22621#returns) states:
> The profile for the connection currently used to connect the machine to the Internet, or null if there is no connection profile with a suitable connection.

Here is an example that calls this method (make sure you are disconnected from the internet):
```dart
import 'package:win32/winrt.dart';

class ConnectionProfile extends IInspectable {
  ConnectionProfile.fromRawPointer(super.ptr);
}

ConnectionProfile getInternetConnectionProfile() {
  final activationFactoryPtr = CreateActivationFactory(
      'Windows.Networking.Connectivity.NetworkInformation',
      IID_INetworkInformationStatics);
  final object =
      INetworkInformationStatics.fromRawPointer(activationFactoryPtr);

  try {
    return ConnectionProfile.fromRawPointer(
        object.getInternetConnectionProfile());
  } finally {
    object.release();
  }
}

void main() {
  final profile = getInternetConnectionProfile();
  print(profile.runtimeClassName); // The program will exit with an Access Violation error code
}
```

There is no information on WinMD files on whether a method/property can return null or not. That's why we need to mark methods/properties that return WinRT objects (except async delegates e.g. `IAsyncAction`, collection interfaces e.g. `IVector`, `IMap` etc., and methods from `XXFactory` interfaces) as nullable (see https://github.com/microsoft/windows-rs/issues/331).

I actually did a similar thing in #465. FileOpenPicker's pickSingleFileAsync() returns `IAsyncOperation<StorageFile>`. Since the type argument is a WinRT object, we consider it nullable and expose it as `Future<StorageFile?>`. As pickMultipleFilesAsync() returns `IAsyncOperation<IVectorView<StorageFile>>` and the type argument is a collection interface we don't consider it nullable and expose it as `Future<List<StorageFile>>`.

**Comment by timsneath** [comment]
Yuck. I don't love it, but I also see that it's necessary! Thanks for catching this.

**Comment by halildurmus** [comment]
Yep, I hate it too :(.
