### ISSUE TITLE
ExtractAssociatedIcon (Lost connection to device)

### ISSUE THREAD

**Issue by hootyjeremy** [halildurmus/win32#657]
I am not quite sure how to use this function. I am trying to get the associated icon for a file on the files system. I have tried implementing the code from the tests which show that it is a function but I don't know how to actually use it to get an icon. With what I have now, the debugger quits with an error of `Lost connection to device`.

I'm sure that I'm making a mistake in this code but what am I doing wrong? How do I create the `hInst`, `Pointer<Utf16>` and `Pointer<Uint16>` objects to pass to `ExtractAssociatedIcon`? If you could just point me in the right direction. 

```dart
  final shell32 = DynamicLibrary.open('shell32.dll');

  Pointer<Uint16> pointerUint16 = Pointer.fromAddress(0);

  ExtractAssociatedIcon(GetModuleHandle(nullptr),
      'c:\\AVScanner.ini'.toNativeUtf16(), pointerUint16);
```

Also, the microsoft documentation for `ExtractAssociatedIconW` says `When it is no longer needed, the caller is responsible for freeing the icon handle returned by ExtractAssociatedIcon by calling the [DestroyIcon] function.` Is that something that we would need to do somewhere so that we don't get memory leaks?

**Comment by halildurmus** [comment]
> I am not quite sure how to use this function. I am trying to get the associated icon for a file on the files system. I have tried implementing the code from the tests which show that it is a function but I don't know how to actually use it to get an icon. With what I have now, the debugger quits with an error of Lost connection to device.

I can't help you with this as I don't know how to use this function.

> I'm sure that I'm making a mistake in this code but what am I doing wrong? How do I create the `hInst`, `Pointer<Utf16>` and `Pointer<Uint16>` objects to pass to `ExtractAssociatedIcon`? If you could just point me in the right direction.

You are assigning `nullptr` to the `pointerUint16` variable. In order to allocate memory, you need to use `calloc` from [package:ffi](https://pub.dev/packages/ffi) and call `calloc.free` function to release the allocated memory after you're done with it:

```dart
import 'dart:ffi';

import 'package:ffi/ffi.dart';
import 'package:win32/win32.dart';

void main() {
  final hInstance = GetModuleHandle(nullptr);
  final piIcon = calloc<Uint16>();
  final iconHandle = ExtractAssociatedIcon(
      hInstance, 'c:\\AVScanner.ini'.toNativeUtf16(), piIcon);

  // Call DestroyIcon after you no longer need iconHandle
  DestroyIcon(iconHandle);

  // Release the allocated memory
  calloc.free(piIcon);
}

```
> Also, the microsoft documentation for `ExtractAssociatedIconW` says `When it is no longer needed, the caller is responsible for freeing the icon handle returned by ExtractAssociatedIcon by calling the [DestroyIcon] function.` Is that something that we would need to do somewhere so that we don't get memory leaks?

Yes, you need to call `DestroyIcon` with the icon handle returned from the `ExtractAssociatedIcon` function once you are done using it.

**Comment by hootyjeremy** [comment]
Ah, thanks a lot. I'm in over my head with shell32 stuff. I have done this in C# many years ago but how does the icon handle translate into an image that can be displayed in flutter? Is the `iconHandle` an image? I get these values from the objects but I'm not sure how to create an image in flutter from these. Is that what this function does?

![image](https://user-images.githubusercontent.com/68588318/211954869-890458f3-6da0-40a1-a032-e1e7a42ec58d.png)

**Comment by halildurmus** [comment]
> Ah, thanks a lot. I'm in over my head with shell32 stuff. I have done this in C# many years ago but how does the icon handle translate into an image that can be displayed in flutter? Is the `iconHandle` an image? I get these values from the objects but I'm not sure how to create an image in flutter from these. Is that what this function does?
> 
> ![image](https://user-images.githubusercontent.com/68588318/211954869-890458f3-6da0-40a1-a032-e1e7a42ec58d.png)

You need to do _a lot_ more low-level stuff to display an image in Flutter from the icon handle.

I managed to create an example for this (unfortunately, the icon's background is not transparent):
```dart
import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';
import 'package:flutter/material.dart';
import 'package:win32/win32.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MainPage(),
    );
  }
}

class MainPage extends StatefulWidget {
  const MainPage({super.key});

  @override
  MainPageState createState() => MainPageState();
}

class MainPageState extends State<MainPage> {
  Uint8List? bytes;

  /// Extracts the icon from the given [path] and returns the bytes of the
  /// created BMP.
  ///
  /// To display the image, use the [Image.memory] widget:
  /// ```dart
  /// Image.memory(getEncodedImageBytes(r'c:\windows\regedit.exe')!);
  /// ```
  Uint8List? getEncodedImageBytes(String path) {
    final hInstance = GetModuleHandle(nullptr);
    final pLocation = path.toNativeUtf16();
    final piIcon = calloc<Uint16>();
    final hIcon = ExtractAssociatedIcon(hInstance, pLocation, piIcon);
    if (hIcon == NULL) {
      print('ExtractAssociatedIcon failed.');
      return null;
    }

    final pIconInfo = calloc<ICONINFO>();
    if (GetIconInfo(hIcon, pIconInfo) == FALSE) {
      print('GetIconInfo failed.');
      return null;
    }

    final bmp = calloc<BITMAP>();
    if (GetObject(pIconInfo.ref.hbmColor, sizeOf<BITMAP>(), bmp) == NULL) {
      print('GetObject failed.');
      return null;
    }

    final bitmapFileHeader = calloc<BITMAPFILEHEADER>();
    final bitmapInfoHeader = calloc<BITMAPINFOHEADER>()
      ..ref.biSize = sizeOf<BITMAPINFOHEADER>()
      ..ref.biWidth = bmp.ref.bmWidth
      ..ref.biHeight = bmp.ref.bmHeight
      ..ref.biPlanes = 1
      ..ref.biBitCount = 32
      ..ref.biCompression = BI_RGB;

    final dwBmpSize =
        ((bmp.ref.bmWidth * bitmapInfoHeader.ref.biBitCount + 31) /
                32 *
                4 *
                bmp.ref.bmHeight)
            .toInt();

    final hdc = GetDC(NULL);
    final lpBitmap = calloc<Uint8>(dwBmpSize);
    GetDIBits(hdc, pIconInfo.ref.hbmColor, 0, bmp.ref.bmHeight, lpBitmap,
        bitmapInfoHeader.cast(), DIB_RGB_COLORS);

    final dwSizeOfDIB =
        dwBmpSize + sizeOf<BITMAPFILEHEADER>() + sizeOf<BITMAPINFOHEADER>();
    bitmapFileHeader.ref.bfOffBits =
        sizeOf<BITMAPFILEHEADER>() + sizeOf<BITMAPINFOHEADER>();

    bitmapFileHeader.ref.bfSize = dwSizeOfDIB;
    bitmapFileHeader.ref.bfType = 0x4D42; // BM

    final bytes = (BytesBuilder()
          ..add(Pointer<Uint8>.fromAddress(bitmapFileHeader.address)
              .asTypedList(sizeOf<BITMAPFILEHEADER>()))
          ..add(Pointer<Uint8>.fromAddress(bitmapInfoHeader.address)
              .asTypedList(sizeOf<BITMAPINFOHEADER>()))
          ..add(lpBitmap.asTypedList(dwBmpSize)))
        .toBytes();

    DeleteObject(pIconInfo.ref.hbmColor);
    DeleteObject(pIconInfo.ref.hbmMask);
    DestroyIcon(hIcon);
    ReleaseDC(NULL, hdc);

    free(pIconInfo);
    free(bmp);
    free(pLocation);
    free(piIcon);
    free(bitmapFileHeader);
    free(bitmapInfoHeader);
    free(lpBitmap);

    return bytes;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: bytes == null ? const SizedBox() : Image.memory(bytes!),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            bytes = getEncodedImageBytes(r'c:\windows\regedit.exe');
          });
        },
        mini: true,
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

Preview:
![Untitled](https://user-images.githubusercontent.com/45524029/212051019-130f07f0-84ee-46da-aeaa-33d27c6a5add.png)

**Comment by halildurmus** [comment]
It looks like you'll be able to achieve this with the [WinRT APIs](https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getthumbnailasync?view=winrt-22621#windows-storage-storagefile-getthumbnailasync(windows-storage-fileproperties-thumbnailmode)), but we still have some work to do before you can use these APIs.

![Untitled](https://user-images.githubusercontent.com/45524029/212108324-97230cd6-0bea-4e7e-9e2f-c3c21934f826.png)

**Comment by hootyjeremy** [comment]
Thanks a lot for the information. I might try the non-transparent for now as a placeholder. I'm wondering if I could just scrape a lot of icons in a language I'm familiar with and then create a repo as a half-measure in the meantime. I could probably do that faster than learning win32 c++ :)

Anyway, this was extremely helpful and thanks for your time.

**Comment by Far-Se** [comment]
hi @hootyjeremy , you can try https://github.com/Far-Se/win32audio to extract icons, it's on Extra functions at the end of the page.

**Comment by hootyjeremy** [comment]
I will check it out. Thanks a lot. @Far-Se
