### ISSUE TITLE
How to return a value of type Uint32?

### ISSUE THREAD

**Issue by JasperSurmont** [halildurmus/win32#659]
To use the [EnumWindows](https://pub.dev/documentation/win32/latest/winrt/EnumWindows.html) function, a callback function of type `BOOL Function(HWND, LPARAM)` is required (and BOOL is equal to Uint32).

In the callback function, you need to be able to return either true or false (or 0 / 1). However, how am I supposed to do this? Uint32 is not constructable.

**Comment by halildurmus** [comment]
See this example: https://github.com/timsneath/win32/blob/0a2551be5c31935e72f45108816d48a18355f8e7/example/window.dart#L12-L36

**Comment by JasperSurmont** [comment]
Thanks, sorry I missed this example.
