### ISSUE TITLE
How to display another page of flutter to the extension screen?

### ISSUE THREAD

**Issue by Dboy233** [halildurmus/win32#668]
How to display another page of flutter to the extension screen？

I have two monitors, and when I open another page, I want to actively display the page on another screen. 
Is there a corresponding API operation? 

I am an Android developer and don't know much about the operation of windwos.

**Comment by timsneath** [comment]
This is blocked by the absence of multiple windows, which is a feature in early preview: https://www.youtube.com/watch?v=vtB-teu57vw

When we have multiple window support, you'll be able to use this package to programmatically move a window from one desktop to another.
