### ISSUE TITLE
Missing GetMessageW

### ISSUE THREAD

**Issue by PlugFox** [halildurmus/win32#672]
Missing [GetMessageW](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagew), right now only `GetMessage` available

**Comment by halildurmus** [comment]
This package strips the `W` postfix in functions so `GetMessageW` is exposed as `GetMessage`. When you call `GetMessage`, it calls `GetMessageW` under the hood:

https://github.com/timsneath/win32/blob/bae2d9480e8db92ffec437e00d933154bf49c071/lib/src/win32/user32.g.dart#L3134-L3150
