### ISSUE TITLE
DPAPI is not exported

### ISSUE THREAD

**Issue by yfakariya** [halildurmus/win32#673]
As of #554, DPAPI API was implemented in `lib/src/win32/crypt32.g.dart` , but these are not exported in `lib/win32.dart`.
And some packages still uses (and restricts) to use ver. 3.x (for example, [path_provider](https://github.com/flutter/packages/blob/a9ccbc2928633d9f0fe72590c922fa79080007bd/packages/path_provider/path_provider_windows/pubspec.yaml#L24) ), so I want to request backport to 3.x.

**Comment by timsneath** [comment]
This should be fixed in v3.1.4 and v4.1.2. LMK if you have any issues. Thanks for the bug report!
