### ISSUE TITLE
Support Windows UI Automation APIs

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/win32#710]
This is part of a request by a user at https://github.com/dart-windows/dartwinrt/issues/204.

These APIs can be found in [uiautomationclient.h header](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/).

**Comment by ghost** [comment]
I looked into the [uiautomationclient.h header](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/). It only contains interfaces. Each interface have their own methods. Does dart ffi actually support wrapping C++ features such as interface?

An example would be this [IUIAutomationElement::FindFirst](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationelement-buildupdatedcache) method in uiautomationclient.h, can we directly wrap it like how the [BluetoothDisplayDeviceProperties](https://learn.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothdisplaydeviceproperties) function that is being wrapped [here](https://github.com/dart-windows/win32/blob/12cab55077e6740645295ec401bb098857853cdd/tool/win32gen/data/win32_functions.json#L186) in this repo? 

Thanks!

**Comment by halildurmus** [comment]
> I looked into the [uiautomationclient.h header](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/). It only contains interfaces. Each interface have their own methods. Does dart ffi actually support wrapping C++ features such as interface?

COM interfaces are implemented using a mechanism called a virtual function table, commonly referred to as a vtable. A vtable is a data structure that contains function pointers corresponding to the methods defined in the interface. Each COM interface has its own vtable. By leveraging the information provided by the [Windows Medata](https://github.com/microsoft/win32metadata), we can generate projections of these COM interfaces.

See the COM interfaces [here](https://github.com/dart-windows/win32/tree/main/lib/src/com) that we currently support.

> An example would be this [IUIAutomationElement::FindFirst](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationelement-buildupdatedcache) method in uiautomationclient.h, can we directly wrap it like how the [BluetoothDisplayDeviceProperties](https://learn.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothdisplaydeviceproperties) function that is being wrapped [here](https://github.com/dart-windows/win32/blob/12cab55077e6740645295ec401bb098857853cdd/tool/win32gen/data/win32_functions.json#L186) in this repo?

Here's how the [UIAutomationElement::FindFirst](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationelement-findfirst) method will be generated:

```dart
  int findFirst(int scope, Pointer<COMObject> condition,
          Pointer<Pointer<COMObject>> found) =>
      ptr.ref.vtable
              .elementAt(5)
              .cast<
                  Pointer<
                      NativeFunction<
                          Int32 Function(
                              Pointer,
                              Int32 scope,
                              Pointer<COMObject> condition,
                              Pointer<Pointer<COMObject>> found)>>>()
              .value
              .asFunction<
                  int Function(Pointer, int scope, Pointer<COMObject> condition,
                      Pointer<Pointer<COMObject>> found)>()(
          ptr.ref.lpVtbl, scope, condition, found);
```

**Comment by ghost** [comment]
Thanks for the awesome work done for this! @halildurmus
