### ISSUE TITLE
How to allocate memory for a Utf16 encoded string as an output argument passing into a C native function?

### ISSUE THREAD

**Issue by ghost** [halildurmus/win32#716]
I have the following dart function:

```dart
String getTextFromTextPattern(IUIAutomationTextPattern textPattern) {
  final pTextRange = textPattern.documentRange;
  final textRange = IUIAutomationTextRange(pTextRange);
   
  final pText = calloc<Utf16>();
  final hr = textRange.getText(-1, pText.cast());
  if (FAILED(hr)) {
    free(pText);
    throw WindowsException(hr, message: "[getTextFromTextPattern] Failed to get text from text range");
  }
   
  final text = pText.toDartString();
  print("Found text: $text");
   
  return text;
}
```
The `getText` method's signature on line 6 is:
```dart
int getText(int maxLength, Pointer<Pointer<Utf16>> text)
```

When I call the `getTextFromTextPattern` function, I get an error:
```
Error: Expected type 'Utf16' to be a valid and instantiated subtype of 'NativeType'.
```

This error is saying line 5 is not properly allocating memory for a native Uft16 string in C. What is the proper way to do that? Or is there anything I'm doing fundamentally wrong here? 

Thanks!

**Comment by halildurmus** [comment]
You're trying to pass a `Pointer<Utf16>` type to the `getText` method, but it actually expects a `Pointer<Pointer<Utf16>>` type. 

Here is the updated version of your function:

```dart
String getTextFromTextPattern(IUIAutomationTextPattern textPattern) {
  final pTextRange = textPattern.documentRange;
  final textRange = IUIAutomationTextRange(pTextRange);

  final pText = calloc<Pointer<Utf16>>();

  try {
    final hr = textRange.getText(-1, pText);
    if (FAILED(hr)) {
      throw WindowsException(
        hr,
        message: "[getTextFromTextPattern] Failed to get text from text range",
      );
    }

    final text = pText.value.toDartString();
    print("Found text: $text");

    return text;
  } finally {
    free(pText);
  }
}
```

**Comment by ghost** [comment]
@halildurmus  thanks for the suggestion. The solution make sense, but it doesn't seem to work.

The `textRange.getText(-1, pText)` call doesn't return anything. I've added two prints flanking that line, like

```
  print("Before getText");
  final hr = textRange.getText(-1, pText);
  print("After getText");
```

I only see the "Before getText" printed in the console. 

I looked up the [MS documentation](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationtextrange-gettext#syntax) for `getText`, the second parameter is a `BSTR*` type. 

How do we make sure the Utf16 double pointer we instantiate can be treated as a BSTR* by native C function?

**Comment by halildurmus** [comment]
> I only see the "Before getText" printed in the console.

That sounds like a crash to me. I believe your program crashes because either the `textPattern` being passed to the function _or_ the pointer returned from the `textPattern.documentRange` has a null vtable pointer. 

To confirm my suspicion, can you add the below print statements:

```dart
String getTextFromTextPattern(IUIAutomationTextPattern textPattern) {
   print('textPattern has null vtable pointer: ${textPattern.ptr.ref.isNull}');
   final pTextRange = textPattern.documentRange;
   print('pTextRange has null vtable pointer: ${pTextRange.ref.isNull}');
   final textRange = IUIAutomationTextRange(pTextRange);
  ...
```

If your `textPattern` has a null vtable pointer, that would indicate the `IUIAutomationElement` you are using does not support the text pattern.

To ensure that an `IUIAutomationElement` supports the text pattern, call the `isControlPatternAvailable` method like the example below:

```dart
/// Takes a Control Pattern Availability [propertyId] (e.g.
/// `UIA_IsTextPatternAvailablePropertyId`) and checks if the given [element]
/// supports that particular control pattern.
bool isControlPatternAvailable(int propertyId, IUIAutomationElement element) {
  final retVal = calloc<VARIANT>();
  VariantInit(retVal);
  retVal.ref.vt = VARENUM.VT_BOOL;

  try {
    final hr = element.getCurrentPropertyValue(propertyId, retVal);
    if (FAILED(hr)) throw WindowsException(hr);
    return retVal.ref.boolVal;
  } finally {
    VariantClear(retVal);
    free(retVal);
  }
}

IUIAutomationTextPattern getTextPattern(IUIAutomationElement element) {
  if (!isControlPatternAvailable(
      UIA_IsTextPatternAvailablePropertyId, element)) {
    throw Exception('Text pattern is not available for this element');
  }

  final pPattern = calloc<COMObject>();
  final hr = element.getCurrentPattern(UIA_TextPatternId, pPattern.cast());
  if (FAILED(hr)) {
    free(pPattern);
    throw WindowsException(hr);
  }

  if (pPattern.ref.isNull) {
    free(pPattern);
    throw Exception('Could not get the text pattern');
  }

  return IUIAutomationTextPattern(pPattern);
}
```

If `pTextRange` is the one with a null vtable pointer, I don't know what this would mean as the documentation of [IUIAutomationTextPattern::get_DocumentRange](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationtextpattern-get_documentrange) doesn't mention in which cases this might return null.

Regardless, whenever you receive a `Pointer<COMObject>`, you should always make sure it doesn't have a null vtable pointer by checking its `.ref.isNull` property before using it in your program otherwise it may lead to a crash like in your case.

**Comment by ghost** [comment]
Cool. Thanks for these advice. 

I've added the `isControlPatternAvailable` check in `getTextPattern` function. It did not throw exception.

I've also added the `null` checks for both `textPattern` and `pTextRange` in `getTextFromTextPattern` function, they are both false:

```
textPattern has null vtable pointer: false
pTextRange has null vtable pointer: false
Before getText
```

Is there any way that we can get the crash error message from the native function? Or there is no way because we can't access the native source code?

**Comment by halildurmus** [comment]
OK, I have identified the problem &mdash; it's a Pointer issue. To be more specific, the `documentRange` getter of the `IUIAutomationTextPattern` is incorrectly generated.

I'll fix this shortly. Thanks for your cooperation throughout this process.

> Is there any way that we can get the crash error message from the native function? Or there is no way because we can't access the native source code?

I don't know if this is possible.

**Comment by ghost** [comment]
Sounds good. Thanks!

Could you share how did you identify the issue? I have spend a whole week on this now. It would be nice to learn some technique to systematically trouble shoot such issue, so I'm not slow down by it so much next time.
