### ISSUE TITLE
New Package: win32_gui

### ISSUE THREAD

**Issue by gmpassos** [halildurmus/win32#744]
FYI:

`win32_gui`

Win32 API GUI in Object-Oriented style with some helpers. Uses package [win32](https://pub.dev/packages/win32) and [dart:ffi](https://api.dart.dev/stable/latest/dart-ffi/dart-ffi-library.html).

https://pub.dev/packages/win32_gui

https://github.com/gmpassos/win32_gui

**Comment by domesticmouse** [comment]
Is this worth linking from the README?
