### ISSUE TITLE
Add support for window ocr

### ISSUE THREAD

**Issue by alihassan143** [halildurmus/win32#779]
window 11 ocr api
[Ocr ](https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/OCR)

**Comment by halildurmus** [comment]
[Windows.Media.Ocr](https://learn.microsoft.com/uwp/api/windows.media.ocr) is a Windows Runtime (WinRT) API and is outside the scope of this project. This project focuses only on Win32 and COM APIs.

[dartwinrt](https://github.com/dart-windows/dartwinrt) project, on the other hand, is centered around WinRT APIs and includes support for the Ocr API.

An illustrative example can be found [here](https://github.com/dart-windows/dartwinrt/blob/72e374e96785e4ca0387ddeb910c1145b7731c7d/packages/windows_media/example/ocr.dart).
