### ISSUE TITLE
Confusion between ISPVoice and ISpeechVoice

### ISSUE THREAD

**Issue by Keithcat1** [halildurmus/win32#792]
Currently, we have 2 classes that seem to be the same thing. [ISPVoice](https://pub.dev/documentation/win32/latest/win32/ISpVoice-class.html) and [ISpeechVoice](https://pub.dev/documentation/win32/latest/win32/ISpeechVoice-class.html). These appear to be the same thing, as Microsoft docs always seems to call it ISPVoice. However, if I want to use GetVoices, I have to use ISpeechVoice. While moving, I discovered that whereas ISPVoice.GetStatus returns a Pointer<SPVOICESTATUS>, ISpeechVoice.status returns a Pointer<ComObject> and I don't dare cast it because SPVOICESTATUS is a struct, not a ComObject and my code uses it to check if SAPI is speaking. Would it be possible to simply add GetVoices to ISPVoice or am I missing something?

**Comment by halildurmus** [comment]
> Currently, we have 2 classes that seem to be the same thing. [ISPVoice](https://pub.dev/documentation/win32/latest/win32/ISpVoice-class.html) and [ISpeechVoice](https://pub.dev/documentation/win32/latest/win32/ISpeechVoice-class.html). These appear to be the same thing, as Microsoft docs always seems to call it ISPVoice.

Unfortunately, current Microsoft documentation does not offer clear guidance on the distinction between the two. However, I found an old documentation that appears to be for `ISpeechVoice` [here](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms723602(v=vs.85)).

> However, if I want to use GetVoices, I have to use ISpeechVoice. While moving, I discovered that whereas ISPVoice.GetStatus returns a Pointer, ISpeechVoice.status returns a Pointer and I don't dare cast it because SPVOICESTATUS is a struct, not a ComObject and my code uses it to check if SAPI is speaking. 

The documentation mentions that the [Status](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms723612(v=vs.85)) property of `ISpeechVoice` returns the [ISpeechVoiceStatus](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms722539(v=vs.85)) interface, which is currently not generated. I plan to add this missing interface and a few more missing constants tomorrow.

> Would it be possible to simply add GetVoices to ISPVoice or am I missing something?

That's not possible. All COM interfaces in this project are generated from [win32metadata](https://github.com/microsoft/win32metadata), which contains information about the methods and properties of COM interfaces. The code generation process is limited to the information provided in the metadata, and additional methods cannot be manually added to interfaces.

**Comment by Keithcat1** [comment]
Thanks. The example is nice as well.
