### ISSUE TITLE
Add screenshots for examples

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#8]

**Comment by RaiAnsar** [comment]
Here's a screenshot of tetris in action, even though never _figured out_ that pause button..
![image](https://user-images.githubusercontent.com/35567562/78076890-bf61e380-73c0-11ea-930d-3933e2987f12.png)

**Comment by RaiAnsar** [comment]
Simple paint sample Example Screenshot..
![image](https://user-images.githubusercontent.com/35567562/78077082-28495b80-73c1-11ea-8612-c30de38d748d.png)

**Comment by RaiAnsar** [comment]
Simple console
![image](https://user-images.githubusercontent.com/35567562/78077170-5038bf00-73c1-11ea-8aca-4cae2050d49b.png)

**Comment by RaiAnsar** [comment]
Tetris more Screenshots: 
![image](https://user-images.githubusercontent.com/35567562/78077379-bc1b2780-73c1-11ea-854a-e2cda9013484.png)
