### ISSUE TITLE
Error when build iOS 

### ISSUE THREAD

**Issue by kostricanitechnology** [halildurmus/win32#811]
Hello, I am getting the following error when I try to release my app on iPhone 

Running Xcode build...                                                  
Xcode build done.                                           58.5s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/win32-5.2.0/lib/win32.dart:1:1: Error: The specified language version is too high. The highest
supported language version is 3.1.

I have updated the flutter and package but same issue

**Comment by halildurmus** [comment]
`win32` v5.2.0 requires Dart version `3.2.0` or higher. Therefore, your Flutter version should be at least `3.16.0`.

Could you please provide the output of running `flutter doctor -v`?

**Comment by kostricanitechnology** [comment]
Yes below you can find the results from Flutter Doctor -v

[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-AL)
    • Flutter version 3.13.9 on channel stable at /Users/alfonsmala/Documents/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
    • Android SDK at /Users/alfonsmala/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by halildurmus** [comment]
Thank you. You need to upgrade your Flutter version by running `flutter upgrade`.

**Comment by kostricanitechnology** [comment]
since I cannot upgrade the flutter because there are issues with other packages, can I downgrade the win32 package to accept my flutter version?

**Comment by halildurmus** [comment]
Yes! You can downgrade `win32` to `5.1.1` by adding this to your `pubspec.yaml` file:
```yaml
dependency_overrides:
  win32: 5.1.1
```

**Comment by kostricanitechnology** [comment]
thank you so much. It worked now :)
