### ISSUE TITLE
Migrate away from `elementAt` when Dart 3.3 is out.

### ISSUE THREAD

**Issue by dcharkes** [halildurmus/win32#815]
`elementAt` has been deprecated as of Dart 3.3 and should be replaced by `operator +`.

https://github.com/dart-windows/win32/blob/a78ff108fbf54927b0334c1bab8f15526c24cbf8/lib/src/com/iapplicationactivationmanager.dart#L46

Valid SDK bound for using `operator +`: `"version:3.3.0-279.1.beta"`.

**Comment by dcharkes** [comment]
@halildurmus What is package:win32's policy on tracking beta releases? Can we submit a PR to migrate already now, or would we need to wait until Dart 3.3 is out?

**Comment by halildurmus** [comment]
I see that the [CL](https://dart-review.googlesource.com/c/sdk/+/346380) was reverted due to this issue. I plan to prepare a PR for the migration and publish a new version today.

**Comment by dcharkes** [comment]
> I see that the [CL](https://dart-review.googlesource.com/c/sdk/+/346380) was reverted due to this issue. I plan to prepare a PR for the migration and publish a new version today.

No hurry. There is more than one package that needs to migrate. And due to the SDK support older language versions (https://github.com/dart-lang/sdk/issues/54250#issuecomment-1903948595) we might not be able to delete the method at all.
