### ISSUE TITLE
Compared to Microsoft's official PROPVARIANT structure, the Win32 library's PROPVARIANT class lacks union content. How should I call blob related?

### ISSUE THREAD

**Issue by android-dev2015** [halildurmus/win32#844]
![image](https://github.com/dart-windows/win32/assets/131351222/a1515b4a-290d-46d6-a199-ca42ae0d72d3)
![image](https://github.com/dart-windows/win32/assets/131351222/43e9aae0-ea6d-4967-a6f2-1814c26afa17)

**Comment by halildurmus** [comment]
Fixed in `v5.5.0`.
