### ISSUE TITLE
Add SystemParametersInfo example

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#91]
Lots of fun stuff here to make a cool demo / example out of.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow

**Comment by franzsilva** [comment]
Hey Tim!, any specific demo you would like to see? i know there is this: https://github.com/timsneath/win32/blob/main/example/sysinfo.dart, but not sure if you wanted a more visual demo, or maybe something else? 

Would like to contribute with a demo. Not a c++ developer. but if the API is already there i dont see any problems calling in from dart.

**Comment by timsneath** [comment]
Whatever scratches your itch! Console is fine; I was simply looking at this API and thinking that there are lots of values returned here that might be useful in a platform plugin. Having some examples will help plugin authors add Windows desktop support.

Thank you!
