### ISSUE TITLE
Get high-DPI support working for traditional apps

### ISSUE THREAD

**Issue by timsneath** [halildurmus/win32#99]
Apps like DartNote look fuzzy on a 200% DPI modern device. @clarkezone says there's just an API call we need. I think it's one of the APIs I just added to master; need to test this.

**Comment by clarkezone** [comment]
From memory, SetProcessDPIAwareness (older) or SetThreadDPIAwarenessContext.. also some others you may need eg for non-client scaling and then handling DPIChanged messages.  Will take a look at some point.

**Comment by timsneath** [comment]
I'd forgotten I had this bug open :) 

For historical reference, this is fixed with:
```dart
SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
```

I've added this to utils.dart for ease of use by other apps in a0127d7ced28ba1e80bae799268e848388a87ff9.
